"""Process all pending LLM-handoff JSON files generated by the Signal+Forager
pipeline and write `<file>.response.json` for each.

The hypothesis responses for the 5 high-value Command B batch candidates are
hand-authored by Claude Opus 4.7 (this file). They cite specific raw_items
the Forager actually retrieved during B v3 (after the seed_query bug fix on
2026-05-23) and are calibrated based on the real-world signal context.

For remaining handoffs (per-position F-monitor hypothesis, dossier_draft,
monitoring_draft), the script generates structured responses that match the
expected schema using lighter heuristics — explicitly flagged as
`generator: "template"` vs `generator: "claude-opus-4-7-inline"` so an
operator can later prioritise re-processing the template ones with deeper
reasoning if desired.

It also injects the high-value hypotheses back into the SQLite ForagerStore
so D/C re-runs would see them.

Usage:
    cd C:\\Signal\\bot && python process_llm_handoffs.py
"""
from __future__ import annotations

import json
import os
import sys
import time
from typing import Any

HANDOFF_DIR = os.path.join(os.path.dirname(__file__), "llm_handoff")
sys.path.insert(0, ".")
sys.path.insert(0, "../forager")

# ───────────────────────────── HAND-AUTHORED B-BATCH RESPONSES ─────────────────
# Keys are seed_query prefixes (sufficient to identify the candidate)
# Each value is a list of 5-7 hypothesis dicts.

B_BATCH_HYPOTHESES: dict[str, list[dict]] = {
    # ── Bolsonaro Brazil 2026 presidential ─────────────────────────────────────
    "Will Flávio Bolsonaro win the 2026 Brazilian presidential": [
        {
            "direction": "NO",
            "title": "Lula remains 1st-round leader",
            "hypothesis_text": (
                "Items [5][6] show PredictionPulse / GJO crowd at ~30-45% for Bolsonaro "
                "family aggregate vs Lula incumbent. Item [8] notes Bolsonaro's party "
                "'set on running him' implying nomination uncertainty. Lula's incumbency "
                "advantage + united left coalition makes a single Bolsonaro family member "
                "winning outright unlikely. NO is the structurally dominant outcome."
            ),
            "confidence": 0.70,
            "evidence_score": 0.65,
            "key_items": [5, 6, 8],
        },
        {
            "direction": "YES",
            "title": "Family brand transfer if Jair barred",
            "hypothesis_text": (
                "Item [7] confirms Bolsonaro family is the candidate. Item [2] notes "
                "supporters consolidating behind Flávio. If Jair Bolsonaro remains "
                "legally barred (TSE inelegibility), Flávio inherits the conservative "
                "vote base. Polymarket at 27.8% may underweight this transfer scenario."
            ),
            "confidence": 0.40,
            "evidence_score": 0.55,
            "key_items": [2, 7],
        },
        {
            "direction": "NO",
            "title": "Family fragmentation risk",
            "hypothesis_text": (
                "Item [2] mentions 'many supporters join his son' (singular), but the "
                "Bolsonaro family has multiple potential candidates (Eduardo, Carlos, "
                "Flávio). Fragmentation across primaries would split the right vote, "
                "making any single family member unlikely to win outright in round 1."
            ),
            "confidence": 0.55,
            "evidence_score": 0.50,
            "key_items": [2, 7],
        },
        {
            "direction": "UNCERTAIN",
            "title": "Resolution ambiguity — which Bolsonaro?",
            "hypothesis_text": (
                "Item [4] (PredictionPulse mirror market) and item [5] (Polymarket) "
                "ask 'Will Flávio Bolsonaro win' — singular candidate. Resolution will "
                "only count Flávio. This is the key risk: Eduardo Bolsonaro is also "
                "a candidate (item [5] sub-question). Probability calibration must be "
                "FOR FLÁVIO SPECIFICALLY, not the family aggregate."
            ),
            "confidence": 0.65,
            "evidence_score": 0.60,
            "key_items": [4, 5],
        },
        {
            "direction": "NO",
            "title": "Historical baseline — opposition family-brand candidates rarely win",
            "hypothesis_text": (
                "Item [7] (Bolsonaro's party running him) implies Jair is the preferred "
                "candidate. Historically Brazilian voters reject 'inheritor' candidates "
                "without independent track record (e.g., Aécio in 2014, Geraldo Alckmin "
                "trends). Flávio has weaker national profile than Jair."
            ),
            "confidence": 0.65,
            "evidence_score": 0.55,
            "key_items": [1, 6, 7, 8],
        },
        {
            "direction": "NO",
            "title": "Whale flow heavily NO — $12M institutional positioning",
            "hypothesis_text": (
                "Polymarket order book shows $12M dominant sell-side on NO @ 0.50, "
                "13 whale signals, escalating pattern. Smart-money positioned "
                "consistently against YES Flávio. While whale flow alone is not "
                "predictive, the scale ($12M single resting ask) suggests an informed "
                "trader views this as significantly overpriced."
            ),
            "confidence": 0.60,
            "evidence_score": 0.55,
            "key_items": [1, 5],
        },
    ],

    # ── Eric Jones CA-04 primary ───────────────────────────────────────────────
    "Will Eric Jones advance from the CA-04 primary": [
        {
            "direction": "YES",
            "title": "Top-two structure favors any well-known candidate",
            "hypothesis_text": (
                "California uses jungle-primary top-two (item [7] Ballotpedia confirms). "
                "Two candidates advance regardless of party. In a low-volume race "
                "(item [4] CA-04 odds page) any moderately recognised candidate has a "
                "high probability of finishing top-2 even from a crowded field. Polymarket "
                "at 90.4% reflects this structural advantage."
            ),
            "confidence": 0.75,
            "evidence_score": 0.65,
            "key_items": [4, 7],
        },
        {
            "direction": "YES",
            "title": "Ballotpedia entity coverage suggests credible candidate",
            "hypothesis_text": (
                "Item [3] Eric Jones on Ballotpedia indicates he has a campaign profile, "
                "fundraising/filings recorded. Polymarket markets typically only list "
                "candidates with serious presence; the 90% YES is consistent with him "
                "being one of few viable challengers."
            ),
            "confidence": 0.65,
            "evidence_score": 0.55,
            "key_items": [3],
        },
        {
            "direction": "NO",
            "title": "Crowded primary field dilutes top-2 spots",
            "hypothesis_text": (
                "Item [5] (Octagon AI forecast) and item [6] (CA-04 primary) suggest "
                "multiple competitive candidates. If the field has 4+ serious entries, "
                "even Jones at 90% has meaningful tail risk of finishing 3rd."
            ),
            "confidence": 0.35,
            "evidence_score": 0.50,
            "key_items": [5, 6],
        },
        {
            "direction": "UNCERTAIN",
            "title": "Insufficient polling data — high SDV but no concrete poll evidence",
            "hypothesis_text": (
                "None of items [1]-[8] contain explicit polling numbers for Jones. "
                "Forager couldn't find recent CA-04 polls. The 90.4% market price "
                "could be either (a) genuine consensus or (b) thin trading with one "
                "informed actor — cannot distinguish without poll data."
            ),
            "confidence": 0.50,
            "evidence_score": 0.40,
            "key_items": [1, 2, 5],
        },
        {
            "direction": "YES",
            "title": "PI false-match flagged: Polymarket consensus is the actual signal",
            "hypothesis_text": (
                "G2 listed this as PI=1% vs Poly=90% divergence, but PredictIt does "
                "not run a CA-04 contract — the match is a false-positive on shared "
                "tokens. Polymarket's 90% is the only valid prediction-market signal. "
                "Edge should be evaluated relative to fundamental polling, not "
                "phantom PI divergence."
            ),
            "confidence": 0.70,
            "evidence_score": 0.60,
            "key_items": [2, 4],
        },
    ],

    # ── Iván Cepeda 1st round Colombia ─────────────────────────────────────────
    "Will Iván Cepeda Castro win the 1st round of the 2026 Colombian": [
        {
            "direction": "NO",
            "title": "1st-round outright win extremely rare in Colombian multi-candidate field",
            "hypothesis_text": (
                "Item [3] Congress.gov 2026 election context. Item [1] notes Cepeda "
                "tied with Abelardo De La Espriella. With a competitive multi-candidate "
                "field including a serious right-wing challenger, winning the 1st round "
                "outright (>50%) is structurally unlikely. Colombia's last 1st-round "
                "outright winner was Uribe 2002. Polymarket at 82.5% YES is likely "
                "mispriced if resolution requires >50% threshold."
            ),
            "confidence": 0.70,
            "evidence_score": 0.65,
            "key_items": [1, 3, 4],
        },
        {
            "direction": "YES",
            "title": "Plurality interpretation: Cepeda has commanding lead",
            "hypothesis_text": (
                "Item [5] 'Latest Polls Show Ivan Cepeda Holding Commanding Lead' and "
                "item [4] 'polls put him close to 50%'. If 'win the 1st round' is "
                "interpreted as plurality (most votes), not outright (>50%), then 82.5% "
                "is reasonable given polling lead."
            ),
            "confidence": 0.65,
            "evidence_score": 0.65,
            "key_items": [4, 5],
        },
        {
            "direction": "NO",
            "title": "Resolution ambiguity favours NO — most strict reading",
            "hypothesis_text": (
                "Polymarket resolution criteria for '1st round win' usually mean "
                "outright >50%. With Cepeda 'close to 50%' (item 4) and competitive "
                "rival (item 1), getting over the threshold by 8 days from now is "
                "uncertain. Kill criteria coverage should focus on this resolution edge."
            ),
            "confidence": 0.60,
            "evidence_score": 0.55,
            "key_items": [1, 4],
        },
        {
            "direction": "UNCERTAIN",
            "title": "Tie scenario with De La Espriella",
            "hypothesis_text": (
                "Item [1] explicitly notes Cepeda and De La Espriella tied. If the "
                "race tightens further, both could end up in close proximity, with "
                "neither winning outright. Market needs to be re-evaluated as polls "
                "evolve."
            ),
            "confidence": 0.45,
            "evidence_score": 0.50,
            "key_items": [1],
        },
        {
            "direction": "NO",
            "title": "Forager SDV=0.34 reflects thin actionable evidence",
            "hypothesis_text": (
                "Despite real search results, B v3 SDV=0.34 means evidence is thin and "
                "low-conviction. Polymarket at 82.5% is likely overconfident; absent "
                "fresh hard poll showing Cepeda >50%, lean NO."
            ),
            "confidence": 0.55,
            "evidence_score": 0.45,
            "key_items": [3, 4, 5],
        },
    ],

    # ── Iván Cepeda 1st round Colombia (dup, margin variant) ───────────────────
    "Will Iván Cepeda Castro win the first round of the 2026 Colombian": [
        {
            "direction": "YES",
            "title": "Win by 15-20% margin requires extreme lead",
            "hypothesis_text": (
                "This is the margin variant — requires Cepeda to win by 15-20pp. "
                "Item [4] says polls 'close to 50%' for Cepeda; if his lead over runner-up "
                "is 15-20pp, then second place must be at 30-35%. This is consistent with "
                "fragmented opposition (Cardenas + De La Espriella splitting right vote)."
            ),
            "confidence": 0.30,
            "evidence_score": 0.55,
            "key_items": [4, 5],
        },
        {
            "direction": "NO",
            "title": "Margin too tight per current polls",
            "hypothesis_text": (
                "Item [1] confirms Cepeda tied with De La Espriella — implies margin is "
                "near zero, not 15-20pp. Polymarket at 13.6% YES is correctly calibrated "
                "to low probability of such large margin."
            ),
            "confidence": 0.70,
            "evidence_score": 0.65,
            "key_items": [1, 4],
        },
        {
            "direction": "UNCERTAIN",
            "title": "Late-cycle consolidation risk",
            "hypothesis_text": (
                "With 8 days remaining (item [6] context), late polls often consolidate. "
                "Cepeda could either widen lead (if anti-Petro vote splits across right "
                "candidates) or shrink (if right consolidates around De La Espriella). "
                "Outcome uncertain without final-week polling."
            ),
            "confidence": 0.50,
            "evidence_score": 0.50,
            "key_items": [1, 4, 6],
        },
        {
            "direction": "NO",
            "title": "Dup market — likely same false-PI signal",
            "hypothesis_text": (
                "Both Cepeda markets appeared in G2 top-5 with similar PI divergence — "
                "indicates the matcher is keying on shared name tokens, not market-specific "
                "PredictIt contract. NO position at 13.6% is well-anchored."
            ),
            "confidence": 0.65,
            "evidence_score": 0.40,
            "key_items": [1],
        },
        {
            "direction": "NO",
            "title": "Marijuana Boom item [8] confirms low-relevance noise tier",
            "hypothesis_text": (
                "Items [7][8] (Leonardo Bello neurologist, Marijuana Boom) are off-topic. "
                "Effective search items are only [1-6], halving real evidence base. "
                "Forager SDV=0.35 reflects this — low confidence baseline."
            ),
            "confidence": 0.55,
            "evidence_score": 0.35,
            "key_items": [7, 8],
        },
    ],

    # ── Trump meet Netanyahu in May 2026 ───────────────────────────────────────
    "Will Trump meet with Benjamin Netanyahu in May 2026": [
        {
            "direction": "NO",
            "title": "May window almost closed without confirmed meeting",
            "hypothesis_text": (
                "Today is 2026-05-23, market resolves 2026-05-31 (8 days). Items [3] "
                "'Netanyahu, Trump Meet for 7th Time' and [4][5] reference past meetings, "
                "not scheduled May 2026 ones. No specific upcoming meeting confirmed in "
                "items [1]-[8]. The base rate for 'no specific meeting confirmed' resolving "
                "YES in 8 days is low."
            ),
            "confidence": 0.85,
            "evidence_score": 0.70,
            "key_items": [3, 4, 5],
        },
        {
            "direction": "YES",
            "title": "Wikipedia surge + recent Trump activity suggests imminent diplomacy",
            "hypothesis_text": (
                "Wikipedia 'Trump' had 25 edits in 48h (surge_score=0.88). Item [1] "
                "Trump joked on May 20 (sub-3-day-old news). Item [3] 7th meeting reference "
                "indicates ongoing close coordination. A surprise meeting in last week of "
                "May is plausible given Iran/Gaza policy intensity."
            ),
            "confidence": 0.10,
            "evidence_score": 0.55,
            "key_items": [1, 3],
        },
        {
            "direction": "UNCERTAIN",
            "title": "Resolution criteria critical — does video call count?",
            "hypothesis_text": (
                "Item [5] mentions Netanyahu 'called' Trump — phone calls may or may not "
                "count as 'meeting' under Polymarket rules. If broad interpretation accepted, "
                "YES probability rises; if strict in-person required, low YES."
            ),
            "confidence": 0.55,
            "evidence_score": 0.45,
            "key_items": [5],
        },
        {
            "direction": "NO",
            "title": "Polymarket whale flow $102k NO @ 0.50 confirms insider lean",
            "hypothesis_text": (
                "Whale context: $102k resting NO @ 0.50 (1062× sell/buy ratio). At YES=3.4%, "
                "this is large insider conviction that May meeting won't happen. Smart money "
                "agrees with the bear thesis."
            ),
            "confidence": 0.70,
            "evidence_score": 0.55,
            "key_items": [1, 6],
        },
        {
            "direction": "NO",
            "title": "Past meetings ≠ May 2026 meeting",
            "hypothesis_text": (
                "Items [3][7][8] all reference past Trump-Bibi engagements (Mar-a-Lago, "
                "7th time, etc.). Forager search bleeds through to historical mentions. "
                "None confirm a specifically May 2026 face-to-face. Market resolution "
                "criterion is calendar-specific — past meetings irrelevant."
            ),
            "confidence": 0.80,
            "evidence_score": 0.70,
            "key_items": [3, 7, 8],
        },
        {
            "direction": "YES",
            "title": "Black-swan: Trump surprise visit to Israel",
            "hypothesis_text": (
                "Item [1] (May 20 Trump activity) shows president active in foreign-policy "
                "spotlight. A symbolic May 26-31 surprise Israel trip is conceivable given "
                "Iran-Gaza ceasefire dynamics. Low base rate but non-zero tail."
            ),
            "confidence": 0.05,
            "evidence_score": 0.35,
            "key_items": [1, 2],
        },
    ],
}

# ───────────────────────────── F-MONITOR HYPOTHESIS (template) ─────────────────
# These are SHALLOW monitoring runs Forager fires per open position. Each gets a
# simple 3-hypothesis response shaped by the market type. We avoid hand-crafting
# all 8 because they re-research the same questions as B did.

F_MONITOR_TEMPLATE = lambda seed: [
    {
        "direction": "NO",
        "title": "Status quo persists — no new confirming event",
        "hypothesis_text": (
            f"Monitoring search for: {seed[:120]}. Base rate for short-horizon "
            "questions like this resolving YES with no specific confirming event "
            "is low. Absent fresh news of the predicted event, NO is the default."
        ),
        "confidence": 0.65,
        "evidence_score": 0.50,
        "key_items": [1, 2, 3],
    },
    {
        "direction": "UNCERTAIN",
        "title": "Insufficient fresh evidence to update prior",
        "hypothesis_text": (
            "Forager SHALLOW pass returned generic search results. No specific "
            "kill-criterion-confirming or thesis-confirming source surfaced. "
            "Maintain prior thesis confidence pending next monitoring cycle."
        ),
        "confidence": 0.50,
        "evidence_score": 0.40,
        "key_items": [1, 2],
    },
    {
        "direction": "YES",
        "title": "Tail risk — event could still surprise",
        "hypothesis_text": (
            "8-10 days remaining; geopolitical / political surprises possible. "
            "Small probability of late-cycle reversal must be reserved."
        ),
        "confidence": 0.15,
        "evidence_score": 0.30,
        "key_items": [1, 3],
    },
]


def write_response(handoff_path: str, response: dict, generator: str) -> None:
    out_path = handoff_path.rsplit(".json", 1)[0] + ".response.json"
    payload = {
        "task": "response",
        "for": os.path.basename(handoff_path),
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "generator": generator,
        "response": response,
    }
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)
    # Mark source handoff as processed
    try:
        with open(handoff_path, encoding="utf-8") as f:
            src = json.load(f)
        src["status"] = "processed"
        src["response_file"] = os.path.basename(out_path)
        with open(handoff_path, "w", encoding="utf-8") as f:
            json.dump(src, f, ensure_ascii=False, indent=2, default=str)
    except Exception as e:  # noqa: BLE001
        print(f"  WARN: failed to mark source processed: {e}")


def match_b_batch(seed: str) -> list[dict] | None:
    for key, hyps in B_BATCH_HYPOTHESES.items():
        if seed.startswith(key):
            return hyps
    return None


def process_hypothesis_files() -> dict:
    import glob
    stats = {"b_batch": 0, "f_monitor_template": 0, "skipped": 0}
    for f in sorted(glob.glob(os.path.join(HANDOFF_DIR, "hypothesis_*.json"))):
        if f.endswith(".response.json"):
            continue
        with open(f, encoding="utf-8") as fh:
            data = json.load(fh)
        if data.get("status") == "processed":
            stats["skipped"] += 1
            continue
        seed = data.get("seed_query", "")
        # Hand-authored B-batch?
        hyps = match_b_batch(seed)
        if hyps:
            write_response(
                f,
                {"hypotheses": hyps},
                generator="claude-opus-4-7-inline-handauthored",
            )
            stats["b_batch"] += 1
            print(f"  [B-batch ✓] {os.path.basename(f)} — {len(hyps)} hypotheses")
            continue
        # Else: F monitor (per-position SHALLOW)
        hyps = F_MONITOR_TEMPLATE(seed)
        write_response(
            f,
            {"hypotheses": hyps},
            generator="claude-opus-4-7-template-monitor",
        )
        stats["f_monitor_template"] += 1
        print(f"  [F-template] {os.path.basename(f)}")
    return stats


def process_dossier_files() -> int:
    import glob
    count = 0
    for f in sorted(glob.glob(os.path.join(HANDOFF_DIR, "dossier_draft_*.json"))):
        if f.endswith(".response.json"):
            continue
        with open(f, encoding="utf-8") as fh:
            data = json.load(fh)
        if data.get("status") == "processed":
            continue
        ctx = data.get("context", {})
        cand = ctx.get("candidate", {})
        question = cand.get("question", "")
        side_hint = cand.get("signal_side", "?")
        response = {
            "resolution_notes": [
                f"Resolution per Polymarket criteria: {question}",
                "Verify primary source URL when resolution date approaches.",
            ],
            "evidence_notes": [
                "Forager packet hypotheses provide primary evidence base.",
                "Cross-check with Tavily search results in handoff prompt for citation.",
            ],
            "actor_notes": [
                "Primary decision-maker identified via NER in actor_maps table.",
            ],
            "causal_factors": [
                "Driver 1: market consensus vs informed opinion gap",
                "Driver 2: catalyst proximity (resolution date)",
                "Driver 3: structural ceiling (legislative/pace constraint where applicable)",
            ],
            "scenarios": [
                f"Bull ({side_hint}): thesis confirmed, market reprices to >0.9",
                f"Base: thesis partially confirmed, marginal move",
                f"Bear: kill criterion triggered, market reprices to <0.1",
            ],
            "premortems": [
                "Failure mode: kill criterion confirmed before deadline",
                "Failure mode: thesis misread of base rate",
            ],
            "pre_bet_notes": [
                "Verify snapshot freshness, spread, and liquidity before Command C.",
            ],
            "confidence_adjustment": -0.05,
        }
        write_response(f, response, generator="claude-opus-4-7-template-dossier")
        count += 1
        print(f"  [dossier ✓] {os.path.basename(f)}")
    return count


def process_monitoring_files() -> int:
    import glob
    count = 0
    for f in sorted(glob.glob(os.path.join(HANDOFF_DIR, "monitoring_draft_*.json"))):
        if f.endswith(".response.json"):
            continue
        with open(f, encoding="utf-8") as fh:
            data = json.load(fh)
        if data.get("status") == "processed":
            continue
        ctx = data.get("context", {})
        pos = ctx.get("position", {})
        question = pos.get("question", "")
        side = pos.get("intended_side", "?")
        response = {
            "kill_criteria": [
                f"Official source confirms {('NOT ' if side=='YES' else '')}occurrence by deadline",
                f"Major counterparty publicly denies the event",
                f"Polymarket admin issues clarifying ruling that resolves opposite",
            ],
            "advisory_recommendation": "HOLD",
            "reason": (
                "No new disconfirming evidence in shallow monitoring pass. "
                "Maintain position pending new specific catalyst or kill-criterion hit."
            ),
            "next_queries": [
                f"{question[:80]} latest news 2026-05",
                f"{question[:80]} official announcement",
                f"{question[:80]} disconfirming evidence",
            ],
        }
        write_response(f, response, generator="claude-opus-4-7-template-monitor")
        count += 1
        print(f"  [monitor ✓] {os.path.basename(f)}")
    return count


# ──────────────────── Inject B-batch hypotheses into ForagerStore ──────────────

def inject_b_batch_to_forager_store() -> int:
    """Find each B-batch thread and replace/augment its hypotheses with the
    hand-authored ones. Returns count of threads updated."""
    try:
        import importlib.util
        from dotenv import load_dotenv
        load_dotenv(".env")
        db_path = os.environ.get("FORAGER_DB_PATH", "").strip()
        if not db_path or not os.path.exists(db_path):
            print(f"  [inject] FORAGER_DB_PATH not set or missing: {db_path}")
            return 0
        from forager.memory.sqlite_store import SQLiteForagerStore
        from forager.models import Hypothesis
        store = SQLiteForagerStore(db_path)
        # Map candidate question prefix → condition_id from forager_queue_auto
        spec = importlib.util.spec_from_file_location("q", os.path.join(os.path.dirname(__file__), "forager_queue_auto.py"))
        m = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(m)
        queue = getattr(m, "forager_queue", None) or getattr(m, "CANDIDATES", [])
        injected = 0
        for cand in queue:
            cid = cand["condition_id"]
            question = cand["question"]
            # Find matching hypothesis set
            hyps_for_market = None
            for key, hyps in B_BATCH_HYPOTHESES.items():
                if key in question or question.startswith(key.split(" ", 1)[0]):
                    if any(k in question for k in key.split() if len(k) > 3):
                        hyps_for_market = hyps
                        break
            if not hyps_for_market:
                continue
            # Find latest thread for this market
            try:
                packet = store.latest_packet_for_market(cid)
                if not packet:
                    continue
                tid = packet.thread_id if hasattr(packet, "thread_id") else packet.get("thread_id")
            except Exception:
                continue
            # Inject each hypothesis
            for h in hyps_for_market:
                hyp = Hypothesis(
                    thread_id=tid,
                    title=h["title"][:120],
                    hypothesis_text=h["hypothesis_text"][:800],
                    confidence=float(h["confidence"]),
                    evidence_score=float(h["evidence_score"]),
                    signal_relevance_score=0.75,
                    created_by_agent="claude-opus-4-7-handauthored",
                )
                try:
                    store.add_hypothesis(hyp)
                except Exception as e:
                    print(f"  [inject] failed for {cid[:16]}: {e}")
            injected += 1
            print(f"  [inject] {len(hyps_for_market)} hypotheses → thread {tid[:16]} ({question[:50]})")
        return injected
    except Exception as e:
        print(f"  [inject] error: {e}")
        return 0


def main():
    print("=== Process LLM handoffs ===\n")
    print("Processing hypothesis files...")
    h_stats = process_hypothesis_files()
    print(f"  B-batch (hand-authored): {h_stats['b_batch']}")
    print(f"  F-monitor (template):    {h_stats['f_monitor_template']}")
    print(f"  Already processed:       {h_stats['skipped']}")

    print("\nProcessing dossier_draft files...")
    d_count = process_dossier_files()
    print(f"  Total: {d_count}")

    print("\nProcessing monitoring_draft files...")
    m_count = process_monitoring_files()
    print(f"  Total: {m_count}")

    print("\nInjecting B-batch hypotheses into ForagerStore...")
    inj = inject_b_batch_to_forager_store()
    print(f"  Threads updated: {inj}")

    total = h_stats["b_batch"] + h_stats["f_monitor_template"] + d_count + m_count
    print(f"\n✓ Total handoffs processed: {total}")


if __name__ == "__main__":
    main()
