"""Auto-generated by Stage 0 splitter. Tools registered by mcp_server.register_all(mcp)."""
from __future__ import annotations
import asyncio
import json
import math
from datetime import datetime, timezone

import httpx

import config
import db
from markets import fetch_active_markets

from lib.execution import (
    clamp01 as _clamp01,
    float_or_none as _float_or_none,
    execution_prices as _execution_prices,
    best_executable_edge as _best_executable_edge,
    no_signal_reason as _no_signal_reason,
)
from lib.queries import (
    latest_probability as _latest_probability,
    latest_execution_context as _latest_execution_context,
    market_row as _market_row,
    research_completeness as _research_completeness,
)
from lib.scoring import (
    hidden_gem_score as _hidden_gem_score,
    moonshot_score as _moonshot_score,
    resolution_completeness as _resolution_completeness,
    pre_bet_score as _pre_bet_score,
    signal_quality_score as _signal_quality_score,
    log_score as _log_score,
    quality_grade as _quality_grade,
    parse_dt as _parse_dt,
)
from lib.sizing import recommended_stake as _recommended_stake


def _today() -> str:
    return datetime.now(timezone.utc).date().isoformat()


def _ensure_db() -> None:
    db.init()


SIGNAL_ARCHETYPES = {
    "countable_catalyst",
    "cheap_optionality",
    "resolution_wording_trap",
    "stale_price",
    "actor_incentive_mismatch",
    "crowd_narrative_error",
    "repricing_watch",
}


def register(mcp):
    @mcp.tool()
    def forecast_quality_report() -> dict:
        """
        Score resolved forecasts against outcomes and against the market price.

        Positive market_relative_brier means Claude beat the market snapshot on
        Brier score. Negative means the market was better calibrated.
        """
        _ensure_db()
        with db.connect() as conn:
            rows = conn.execute("""
                SELECT a.id, a.condition_id, a.created_at, a.probability_yes,
                       a.yes_price_at_analysis, a.confidence, a.edge, a.decision,
                       m.question, m.vertical, m.resolved_yes
                FROM analyses a
                JOIN markets m ON m.condition_id = a.condition_id
                WHERE m.resolved = 1 AND m.resolved_yes IS NOT NULL
                ORDER BY a.created_at ASC
            """).fetchall()

        scored = []
        buckets: dict[str, dict[str, float]] = {}
        confidence_buckets: dict[str, dict[str, float]] = {}
        for r in rows:
            outcome = 1.0 if float(r["resolved_yes"]) > 0.5 else 0.0
            p = _clamp01(r["probability_yes"])
            market_p = _clamp01(r["yes_price_at_analysis"])
            brier = (p - outcome) ** 2
            market_brier = (market_p - outcome) ** 2
            log_score = _log_score(p, outcome)
            market_log_score = _log_score(market_p, outcome)
            item = {
                "analysis_id": r["id"],
                "condition_id": r["condition_id"],
                "date": r["created_at"][:10],
                "question": r["question"],
                "vertical": r["vertical"],
                "probability_yes": p,
                "market_price": market_p,
                "outcome_yes": outcome,
                "brier": round(brier, 4),
                "market_brier": round(market_brier, 4),
                "market_relative_brier": round(market_brier - brier, 4),
                "log_score": round(log_score, 4),
                "market_log_score": round(market_log_score, 4),
                "decision": r["decision"],
                "confidence": r["confidence"],
            }
            scored.append(item)

            bucket = f"{int(p * 10) * 10}-{int(p * 10) * 10 + 10}%"
            if p >= 1.0:
                bucket = "90-100%"
            buckets.setdefault(bucket, {"n": 0, "sum_p": 0.0, "sum_y": 0.0, "sum_brier": 0.0})
            buckets[bucket]["n"] += 1
            buckets[bucket]["sum_p"] += p
            buckets[bucket]["sum_y"] += outcome
            buckets[bucket]["sum_brier"] += brier

            conf_bucket = "low" if r["confidence"] < 0.35 else "medium" if r["confidence"] < 0.7 else "high"
            confidence_buckets.setdefault(conf_bucket, {"n": 0, "sum_brier": 0.0, "sum_rel": 0.0})
            confidence_buckets[conf_bucket]["n"] += 1
            confidence_buckets[conf_bucket]["sum_brier"] += brier
            confidence_buckets[conf_bucket]["sum_rel"] += market_brier - brier

        n = len(scored)
        if not n:
            return {
                "resolved_forecasts": 0,
                "message": "No resolved analyses yet. Run resolve_closed after markets close.",
            }

        avg_brier = sum(x["brier"] for x in scored) / n
        avg_market_brier = sum(x["market_brier"] for x in scored) / n
        avg_log = sum(x["log_score"] for x in scored) / n
        avg_market_log = sum(x["market_log_score"] for x in scored) / n
        calibration = [{
            "bucket": k,
            "n": int(v["n"]),
            "avg_forecast": round(v["sum_p"] / v["n"], 3),
            "empirical_yes_rate": round(v["sum_y"] / v["n"], 3),
            "avg_brier": round(v["sum_brier"] / v["n"], 4),
        } for k, v in sorted(buckets.items())]
        confidence = [{
            "bucket": k,
            "n": int(v["n"]),
            "avg_brier": round(v["sum_brier"] / v["n"], 4),
            "avg_market_relative_brier": round(v["sum_rel"] / v["n"], 4),
        } for k, v in sorted(confidence_buckets.items())]

        return {
            "resolved_forecasts": n,
            "avg_brier": round(avg_brier, 4),
            "avg_market_brier": round(avg_market_brier, 4),
            "market_relative_brier": round(avg_market_brier - avg_brier, 4),
            "avg_log_score": round(avg_log, 4),
            "avg_market_log_score": round(avg_market_log, 4),
            "market_relative_log_score": round(avg_market_log - avg_log, 4),
            "calibration_buckets": calibration,
            "confidence_buckets": confidence,
            "best_relative": sorted(scored, key=lambda x: x["market_relative_brier"], reverse=True)[:10],
            "worst_relative": sorted(scored, key=lambda x: x["market_relative_brier"])[:10],
        }



    @mcp.tool()
    def false_negative_review(min_move: float = 0.05, limit: int = 30) -> dict:
        """
        Find no-signal analyses that later moved in the forecast direction or resolved
        in the implied direction. This is missed-alpha review.
        """
        _ensure_db()
        with db.connect() as conn:
            rows = conn.execute("""
                SELECT a.id, a.condition_id, a.created_at, a.probability_yes,
                       a.yes_price_at_analysis, a.confidence, a.edge,
                       a.no_signal_reason, a.reasoning,
                       m.question, m.vertical, m.resolved, m.resolved_yes
                FROM analyses a
                JOIN markets m ON m.condition_id = a.condition_id
                WHERE a.decision = 'no_signal'
                ORDER BY a.created_at DESC
            """).fetchall()
            out = []
            for r in rows:
                latest = conn.execute("""
                    SELECT yes_price, captured_at
                    FROM snapshots
                    WHERE condition_id = ? AND captured_at > ?
                    ORDER BY captured_at DESC LIMIT 1
                """, (r["condition_id"], r["created_at"])).fetchone()
                if not latest:
                    latest = conn.execute("""
                        SELECT yes_price, captured_at
                        FROM snapshots
                        WHERE condition_id = ?
                        ORDER BY captured_at DESC LIMIT 1
                    """, (r["condition_id"],)).fetchone()

                market_p = float(r["yes_price_at_analysis"])
                forecast_p = float(r["probability_yes"])
                implied_side = "YES" if forecast_p >= market_p else "NO"
                price_delta = None
                moved_toward = False
                if latest:
                    price_delta = float(latest["yes_price"]) - market_p
                    moved_toward = price_delta >= min_move if implied_side == "YES" else price_delta <= -min_move

                resolved_correct = None
                if r["resolved"] and r["resolved_yes"] is not None:
                    outcome_side = "YES" if float(r["resolved_yes"]) > 0.5 else "NO"
                    resolved_correct = outcome_side == implied_side

                if not moved_toward and resolved_correct is not True:
                    continue
                out.append({
                    "analysis_id": r["id"],
                    "condition_id": r["condition_id"],
                    "date": r["created_at"][:10],
                    "question": r["question"],
                    "vertical": r["vertical"],
                    "implied_side": implied_side,
                    "market_price": market_p,
                    "probability_yes": forecast_p,
                    "edge": r["edge"],
                    "confidence": r["confidence"],
                    "no_signal_reason": r["no_signal_reason"],
                    "latest_price": float(latest["yes_price"]) if latest else None,
                    "price_delta": round(price_delta, 4) if price_delta is not None else None,
                    "moved_toward_forecast": moved_toward,
                    "resolved_correct": resolved_correct,
                    "reasoning": r["reasoning"],
                })

        out.sort(key=lambda x: abs(x["price_delta"] or 0.0), reverse=True)
        return {
            "count": min(len(out), limit),
            "min_move": min_move,
            "missed_candidates": out[:limit],
        }



    @mcp.tool()
    def market_move_after_analysis(condition_id: str, limit: int = 10) -> dict:
        """
        Compare each analysis to the latest later price snapshot for the same market.
        Useful for detecting stale-price and delayed-reaction opportunities.
        """
        _ensure_db()
        with db.connect() as conn:
            market = conn.execute(
                "SELECT question, vertical, end_date FROM markets WHERE condition_id = ?",
                (condition_id,),
            ).fetchone()
            if not market:
                return {"error": f"market {condition_id} not found"}
            rows = conn.execute("""
                SELECT id, created_at, probability_yes, yes_price_at_analysis,
                       confidence, decision, no_signal_reason
                FROM analyses
                WHERE condition_id = ?
                ORDER BY created_at DESC LIMIT ?
            """, (condition_id, limit)).fetchall()
            out = []
            for r in rows:
                latest = conn.execute("""
                    SELECT yes_price, captured_at
                    FROM snapshots
                    WHERE condition_id = ? AND captured_at > ?
                    ORDER BY captured_at DESC LIMIT 1
                """, (condition_id, r["created_at"])).fetchone()
                if not latest:
                    latest = conn.execute("""
                        SELECT yes_price, captured_at
                        FROM snapshots
                        WHERE condition_id = ?
                        ORDER BY captured_at DESC LIMIT 1
                    """, (condition_id,)).fetchone()
                if not latest:
                    continue
                market_p = float(r["yes_price_at_analysis"])
                forecast_p = float(r["probability_yes"])
                price_delta = float(latest["yes_price"]) - market_p
                implied_side = "YES" if forecast_p >= market_p else "NO"
                moved_toward = price_delta > 0 if implied_side == "YES" else price_delta < 0
                out.append({
                    "analysis_id": r["id"],
                    "analysis_time": r["created_at"],
                    "latest_snapshot_time": latest["captured_at"],
                    "decision": r["decision"],
                    "no_signal_reason": r["no_signal_reason"],
                    "implied_side": implied_side,
                    "analysis_price": market_p,
                    "latest_price": float(latest["yes_price"]),
                    "price_delta": round(price_delta, 4),
                    "moved_toward_forecast": moved_toward,
                    "probability_yes": forecast_p,
                    "confidence": r["confidence"],
                })
        return {
            "condition_id": condition_id,
            "question": market["question"],
            "vertical": market["vertical"],
            "moves": out,
        }



    @mcp.tool()
    def research_completeness_score(condition_id: str) -> dict:
        """
        Score whether a market has enough research structure for a serious hidden-gem review.
        """
        _ensure_db()
        with db.connect() as conn:
            market = conn.execute(
                "SELECT question, vertical, end_date FROM markets WHERE condition_id = ?",
                (condition_id,),
            ).fetchone()
            if not market:
                return {"error": f"market {condition_id} not found"}
            completeness = _research_completeness(conn, condition_id)
        return {
            "condition_id": condition_id,
            "question": market["question"],
            "vertical": market["vertical"],
            "end_date": market["end_date"],
            **completeness,
        }



    @mcp.tool()
    def incomplete_research_queue(limit: int = 20) -> dict:
        """
        List markets with recent analyses or hidden-gem reviews whose research dossier is incomplete.
        """
        _ensure_db()
        with db.connect() as conn:
            rows = conn.execute("""
                SELECT m.condition_id, m.question, m.vertical, m.end_date,
                       MAX(COALESCE(a.created_at, h.created_at, m.last_seen_at)) AS last_touch
                FROM markets m
                LEFT JOIN analyses a ON a.condition_id = m.condition_id
                LEFT JOIN hidden_gem_reviews h ON h.condition_id = m.condition_id
                WHERE a.id IS NOT NULL OR h.id IS NOT NULL
                GROUP BY m.condition_id
                ORDER BY last_touch DESC
                LIMIT 100
            """).fetchall()
            out = []
            for r in rows:
                completeness = _research_completeness(conn, r["condition_id"])
                if completeness["score"] >= 85:
                    continue
                out.append({
                    "condition_id": r["condition_id"],
                    "question": r["question"],
                    "vertical": r["vertical"],
                    "end_date": r["end_date"],
                    "last_touch": r["last_touch"],
                    "score": completeness["score"],
                    "missing": completeness["missing"],
                    "counts": completeness["counts"],
                })
                if len(out) >= limit:
                    break
        return {"count": len(out), "markets": out}



    @mcp.tool()
    def signal_quality_report(limit: int = 20) -> dict:
        """
        Summarize early signal quality reviews: repricing capture, mark-to-market
        returns, grades, and lessons.
        """
        _ensure_db()
        with db.connect() as conn:
            rows = conn.execute("""
                SELECT q.*, m.question, m.vertical, m.end_date
                FROM signal_quality_reviews q
                JOIN markets m ON m.condition_id = q.condition_id
                ORDER BY q.total_score DESC, q.created_at DESC
                LIMIT ?
            """, (limit,)).fetchall()
            all_rows = conn.execute("SELECT * FROM signal_quality_reviews").fetchall()

        if not all_rows:
            return {"count": 0, "message": "No signal quality reviews yet."}

        positive = [r for r in all_rows if (r["mark_to_market_pnl"] or 0) > 0]
        moved = [r for r in all_rows if r["moved_toward_thesis"]]
        avg_score = sum(float(r["total_score"]) for r in all_rows) / len(all_rows)
        avg_roi = sum(float(r["mark_to_market_roi"] or 0.0) for r in all_rows) / len(all_rows)
        total_pnl = sum(float(r["mark_to_market_pnl"] or 0.0) for r in all_rows)
        total_stake = sum(float(r["stake_usd"] or 0.0) for r in all_rows)

        return {
            "count": len(rows),
            "total_reviews": len(all_rows),
            "avg_quality_score": round(avg_score, 2),
            "avg_mark_to_market_roi_pct": round(avg_roi * 100, 1),
            "aggregate_mark_to_market_pnl": round(total_pnl, 2),
            "aggregate_mark_to_market_roi_pct": round(total_pnl / total_stake * 100, 1) if total_stake else None,
            "positive_mtm_rate_pct": round(len(positive) / len(all_rows) * 100, 1),
            "moved_toward_thesis_rate_pct": round(len(moved) / len(all_rows) * 100, 1),
            "reviews": [{
                "review_id": r["id"],
                "condition_id": r["condition_id"],
                "question": r["question"],
                "vertical": r["vertical"],
                "side": r["original_side"],
                "entry_price": r["entry_price"],
                "stake_usd": r["stake_usd"],
                "current_side_price": r["current_side_price"],
                "mark_to_market_pnl": round(float(r["mark_to_market_pnl"] or 0.0), 2),
                "mark_to_market_roi_pct": round(float(r["mark_to_market_roi"] or 0.0) * 100, 1),
                "moved_toward_thesis": bool(r["moved_toward_thesis"]),
                "forecast_edge_at_entry": r["forecast_edge_at_entry"],
                "quality_score": r["total_score"],
                "grade": r["grade"],
                "verdict": r["verdict"],
                "lessons": r["lessons"],
            } for r in rows],
        }


