"""Auto-generated by Stage 0 splitter. Tools registered by mcp_server.register_all(mcp)."""
from __future__ import annotations
import asyncio
import json
import math
from datetime import datetime, timezone

import httpx

import config
import db
from markets import fetch_active_markets

from lib.execution import (
    clamp01 as _clamp01,
    float_or_none as _float_or_none,
    execution_prices as _execution_prices,
    best_executable_edge as _best_executable_edge,
    no_signal_reason as _no_signal_reason,
)
from lib.queries import (
    latest_probability as _latest_probability,
    latest_execution_context as _latest_execution_context,
    market_row as _market_row,
    research_completeness as _research_completeness,
)
from lib.scoring import (
    hidden_gem_score as _hidden_gem_score,
    moonshot_score as _moonshot_score,
    resolution_completeness as _resolution_completeness,
    pre_bet_score as _pre_bet_score,
    signal_quality_score as _signal_quality_score,
    log_score as _log_score,
    quality_grade as _quality_grade,
    parse_dt as _parse_dt,
)
from lib.sizing import recommended_stake as _recommended_stake


def _today() -> str:
    return datetime.now(timezone.utc).date().isoformat()


def _ensure_db() -> None:
    db.init()


SIGNAL_ARCHETYPES = {
    "countable_catalyst",
    "cheap_optionality",
    "resolution_wording_trap",
    "stale_price",
    "actor_incentive_mismatch",
    "crowd_narrative_error",
    "repricing_watch",
}


def register(mcp):
    @mcp.tool()
    def record_actor_map(
        condition_id: str,
        actor_name: str,
        role: str,
        incentives: str,
        actor_type: str = "",
        constraints: str = "",
        likely_action: str = "",
        influence_score: float = 0.5,
        visibility_score: float = 0.5,
        notes: str = "",
    ) -> dict:
        """
        Record one actor who can shape the market outcome.

        Use this to move from headline thinking to incentive thinking. Hidden gems
        often appear when the crowd watches the public narrative but misses who
        actually controls the next step.
        """
        _ensure_db()
        if not actor_name.strip() or not role.strip() or not incentives.strip():
            return {"error": "actor_name, role, and incentives are required"}
        with db.connect() as conn:
            market = _market_row(conn, condition_id)
            if not market:
                return {"error": f"market {condition_id} not found; call fetch_candidates first"}
            actor_id = db.add_actor_map(
                conn,
                condition_id=condition_id,
                created_at=None,
                actor_name=actor_name.strip(),
                actor_type=actor_type or None,
                role=role.strip(),
                incentives=incentives.strip(),
                constraints=constraints or None,
                likely_action=likely_action or None,
                influence_score=_clamp01(influence_score),
                visibility_score=_clamp01(visibility_score),
                notes=notes,
            )
            conn.commit()
        return {
            "ok": True,
            "actor_id": actor_id,
            "condition_id": condition_id,
            "question": market["question"],
            "actor_name": actor_name.strip(),
            "influence_score": _clamp01(influence_score),
            "visibility_score": _clamp01(visibility_score),
        }



    @mcp.tool()
    def record_causal_factor(
        condition_id: str,
        factor_name: str,
        mechanism: str,
        direction: str = "UNKNOWN",
        importance: float = 0.5,
        uncertainty: float = 0.5,
        observable_signal: str = "",
        current_state: str = "",
        next_check_at: str = "",
    ) -> dict:
        """
        Record a causal variable that actually drives the market outcome.

        Direction should be YES, NO, MIXED, or UNKNOWN. The goal is to separate
        narrative from mechanism: what must physically, legally, politically, or
        procedurally happen for the market to resolve.
        """
        _ensure_db()
        direction = direction.upper()
        if direction not in {"YES", "NO", "MIXED", "UNKNOWN"}:
            return {"error": "direction must be YES, NO, MIXED, or UNKNOWN"}
        if not factor_name.strip() or not mechanism.strip():
            return {"error": "factor_name and mechanism are required"}
        with db.connect() as conn:
            market = _market_row(conn, condition_id)
            if not market:
                return {"error": f"market {condition_id} not found; call fetch_candidates first"}
            factor_id = db.add_causal_factor(
                conn,
                condition_id=condition_id,
                created_at=None,
                factor_name=factor_name.strip(),
                mechanism=mechanism.strip(),
                direction=direction,
                importance=_clamp01(importance),
                uncertainty=_clamp01(uncertainty),
                observable_signal=observable_signal or None,
                current_state=current_state or None,
                next_check_at=next_check_at or None,
            )
            conn.commit()
        return {
            "ok": True,
            "factor_id": factor_id,
            "condition_id": condition_id,
            "question": market["question"],
            "factor_name": factor_name.strip(),
            "direction": direction,
            "importance": _clamp01(importance),
            "uncertainty": _clamp01(uncertainty),
        }



    @mcp.tool()
    def record_anomaly(
        condition_id: str,
        anomaly_type: str,
        observation: str,
        why_it_matters: str,
        implied_direction: str = "UNKNOWN",
        severity: float = 0.5,
        confidence: float = 0.5,
        status: str = "open",
        source_url: str = "",
    ) -> dict:
        """
        Record a weird mismatch that may indicate the market is missing something.

        Examples: price did not move after a source update, a key actor stayed
        silent, resolution criteria conflict with headlines, or a procedural step
        is absent.
        """
        _ensure_db()
        implied_direction = implied_direction.upper()
        if implied_direction not in {"YES", "NO", "MIXED", "UNKNOWN"}:
            return {"error": "implied_direction must be YES, NO, MIXED, or UNKNOWN"}
        status = status.lower()
        if status not in {"open", "resolved", "false_alarm"}:
            return {"error": "status must be open, resolved, or false_alarm"}
        if not anomaly_type.strip() or not observation.strip() or not why_it_matters.strip():
            return {"error": "anomaly_type, observation, and why_it_matters are required"}
        with db.connect() as conn:
            market = _market_row(conn, condition_id)
            if not market:
                return {"error": f"market {condition_id} not found; call fetch_candidates first"}
            anomaly_id = db.add_anomaly(
                conn,
                condition_id=condition_id,
                created_at=None,
                anomaly_type=anomaly_type.strip(),
                observation=observation.strip(),
                why_it_matters=why_it_matters.strip(),
                implied_direction=implied_direction,
                severity=_clamp01(severity),
                confidence=_clamp01(confidence),
                status=status,
                source_url=source_url or None,
            )
            conn.commit()
        return {
            "ok": True,
            "anomaly_id": anomaly_id,
            "condition_id": condition_id,
            "question": market["question"],
            "implied_direction": implied_direction,
            "severity": _clamp01(severity),
            "confidence": _clamp01(confidence),
        }



    @mcp.tool()
    def record_scenario(
        condition_id: str,
        scenario_name: str,
        path: str,
        probability: float,
        outcome_side: str = "UNKNOWN",
        key_assumptions: str = "",
        breakpoints: str = "",
        early_warning_signals: str = "",
    ) -> dict:
        """
        Record one path by which the market could resolve.

        Use multiple scenarios per market. This prevents a single elegant thesis
        from hiding weird paths, delay paths, and procedural paths.
        """
        _ensure_db()
        outcome_side = outcome_side.upper()
        if outcome_side not in {"YES", "NO", "AMBIGUOUS", "UNKNOWN"}:
            return {"error": "outcome_side must be YES, NO, AMBIGUOUS, or UNKNOWN"}
        if not scenario_name.strip() or not path.strip():
            return {"error": "scenario_name and path are required"}
        with db.connect() as conn:
            market = _market_row(conn, condition_id)
            if not market:
                return {"error": f"market {condition_id} not found; call fetch_candidates first"}
            scenario_id = db.add_scenario(
                conn,
                condition_id=condition_id,
                created_at=None,
                scenario_name=scenario_name.strip(),
                path=path.strip(),
                probability=_clamp01(probability),
                outcome_side=outcome_side,
                key_assumptions=key_assumptions or None,
                breakpoints=breakpoints or None,
                early_warning_signals=early_warning_signals or None,
            )
            total_prob = conn.execute("""
                SELECT SUM(probability) AS p
                FROM scenario_trees
                WHERE condition_id = ?
            """, (condition_id,)).fetchone()["p"] or 0.0
            conn.commit()
        return {
            "ok": True,
            "scenario_id": scenario_id,
            "condition_id": condition_id,
            "question": market["question"],
            "scenario_name": scenario_name.strip(),
            "outcome_side": outcome_side,
            "probability": _clamp01(probability),
            "scenario_probability_sum": round(total_prob, 4),
            "probability_sum_warning": total_prob < 0.85 or total_prob > 1.15,
        }



    @mcp.tool()
    def record_premortem(
        condition_id: str,
        thesis: str,
        failure_mode: str,
        disconfirming_signal: str,
        probability_if_wrong: float = 0.5,
        mitigation: str = "",
        severity: float = 0.5,
    ) -> dict:
        """
        Force the skeptic pass: if our thesis fails, why did it fail?

        A strong premortem names the specific observation that would kill the thesis.
        This keeps the project from falling in love with clever narratives.
        """
        _ensure_db()
        if not thesis.strip() or not failure_mode.strip() or not disconfirming_signal.strip():
            return {"error": "thesis, failure_mode, and disconfirming_signal are required"}
        with db.connect() as conn:
            market = _market_row(conn, condition_id)
            if not market:
                return {"error": f"market {condition_id} not found; call fetch_candidates first"}
            premortem_id = db.add_premortem(
                conn,
                condition_id=condition_id,
                created_at=None,
                thesis=thesis.strip(),
                failure_mode=failure_mode.strip(),
                disconfirming_signal=disconfirming_signal.strip(),
                probability_if_wrong=_clamp01(probability_if_wrong),
                mitigation=mitigation or None,
                severity=_clamp01(severity),
            )
            conn.commit()
        return {
            "ok": True,
            "premortem_id": premortem_id,
            "condition_id": condition_id,
            "question": market["question"],
            "probability_if_wrong": _clamp01(probability_if_wrong),
            "severity": _clamp01(severity),
        }



    @mcp.tool()
    def contrarian_brief(condition_id: str) -> dict:
        """
        Summarize the market's causal/contrarian dossier.

        Use this before hidden-gem review. It answers: who matters, what mechanism
        matters, what looks weird, what paths exist, and how our thesis could fail.
        """
        _ensure_db()
        with db.connect() as conn:
            market = conn.execute(
                "SELECT question, vertical, end_date FROM markets WHERE condition_id = ?",
                (condition_id,),
            ).fetchone()
            if not market:
                return {"error": f"market {condition_id} not found"}
            actors = conn.execute("""
                SELECT actor_name, actor_type, role, incentives, constraints,
                       likely_action, influence_score, visibility_score
                FROM actor_maps
                WHERE condition_id = ?
                ORDER BY influence_score DESC, created_at DESC LIMIT 20
            """, (condition_id,)).fetchall()
            factors = conn.execute("""
                SELECT factor_name, mechanism, direction, importance, uncertainty,
                       observable_signal, current_state, next_check_at
                FROM causal_factors
                WHERE condition_id = ?
                ORDER BY importance DESC, created_at DESC LIMIT 20
            """, (condition_id,)).fetchall()
            anomalies = conn.execute("""
                SELECT anomaly_type, observation, why_it_matters, implied_direction,
                       severity, confidence, status, source_url
                FROM anomalies
                WHERE condition_id = ?
                ORDER BY severity DESC, created_at DESC LIMIT 20
            """, (condition_id,)).fetchall()
            scenarios = conn.execute("""
                SELECT scenario_name, path, probability, outcome_side,
                       key_assumptions, breakpoints, early_warning_signals
                FROM scenario_trees
                WHERE condition_id = ?
                ORDER BY probability DESC, created_at DESC LIMIT 20
            """, (condition_id,)).fetchall()
            premortems = conn.execute("""
                SELECT thesis, failure_mode, disconfirming_signal,
                       probability_if_wrong, mitigation, severity
                FROM premortems
                WHERE condition_id = ?
                ORDER BY severity DESC, created_at DESC LIMIT 20
            """, (condition_id,)).fetchall()
        scenario_sum = sum(float(r["probability"]) for r in scenarios)
        open_anomalies = [r for r in anomalies if r["status"] == "open"]
        return {
            "condition_id": condition_id,
            "question": market["question"],
            "vertical": market["vertical"],
            "end_date": market["end_date"],
            "actor_count": len(actors),
            "causal_factor_count": len(factors),
            "open_anomaly_count": len(open_anomalies),
            "scenario_count": len(scenarios),
            "scenario_probability_sum": round(scenario_sum, 4),
            "premortem_count": len(premortems),
            "actors": [dict(r) for r in actors],
            "causal_factors": [dict(r) for r in factors],
            "anomalies": [dict(r) for r in anomalies],
            "scenarios": [dict(r) for r in scenarios],
            "premortems": [dict(r) for r in premortems],
        }


