"""Auto-generated by Stage 0 splitter. Tools registered by mcp_server.register_all(mcp)."""
from __future__ import annotations
import asyncio
import json
import math
from datetime import datetime, timezone

import httpx

import config
import db
from markets import fetch_active_markets

from lib.execution import (
    clamp01 as _clamp01,
    float_or_none as _float_or_none,
    execution_prices as _execution_prices,
    best_executable_edge as _best_executable_edge,
    no_signal_reason as _no_signal_reason,
)
from lib.queries import (
    latest_probability as _latest_probability,
    latest_execution_context as _latest_execution_context,
    market_row as _market_row,
    research_completeness as _research_completeness,
)
from lib.scoring import (
    hidden_gem_score as _hidden_gem_score,
    moonshot_score as _moonshot_score,
    resolution_completeness as _resolution_completeness,
    pre_bet_score as _pre_bet_score,
    signal_quality_score as _signal_quality_score,
    log_score as _log_score,
    quality_grade as _quality_grade,
    parse_dt as _parse_dt,
)
from lib.sizing import recommended_stake as _recommended_stake


def _today() -> str:
    return datetime.now(timezone.utc).date().isoformat()


def _ensure_db() -> None:
    db.init()


SIGNAL_ARCHETYPES = {
    "countable_catalyst",
    "cheap_optionality",
    "resolution_wording_trap",
    "stale_price",
    "actor_incentive_mismatch",
    "crowd_narrative_error",
    "repricing_watch",
}


def register(mcp):
    @mcp.tool()
    def record_hidden_gem_review(
        condition_id: str,
        thesis: str,
        disconfirming_evidence: str,
        executable_edge: float | None = None,
        liquidity_score: float = 0.5,
        spread_score: float | None = None,
        attention_gap_score: float = 0.5,
        evidence_asymmetry_score: float = 0.5,
        stale_price_score: float = 0.5,
        catalyst_score: float = 0.5,
        resolution_clarity_score: float = 0.5,
        next_check_at: str = "",
        decision: str = "",
    ) -> dict:
        """
        Score whether a market deserves hidden-gem treatment.

        This is deliberately separate from record_analysis. A hidden gem is not just
        "edge exists"; it is a market where public evidence, attention, timing, and
        executable price combine into a researchable opportunity.
        """
        _ensure_db()
        if not thesis.strip():
            return {"error": "thesis is required"}
        if not disconfirming_evidence.strip():
            return {"error": "disconfirming_evidence is required; force a skeptic pass"}

        with db.connect() as conn:
            market = conn.execute(
                "SELECT question FROM markets WHERE condition_id = ?", (condition_id,)
            ).fetchone()
            if not market:
                return {"error": f"market {condition_id} not found; call fetch_candidates first"}

            ctx = _latest_execution_context(conn, condition_id)
            latest_probability = _latest_probability(conn, condition_id)
            if executable_edge is None:
                if ctx is None or latest_probability is None:
                    executable_edge = 0.0
                else:
                    _, executable_edge = _best_executable_edge(
                        latest_probability,
                        ctx["yes_entry_price"],
                        ctx["no_entry_price"],
                    )
            executable_edge = max(0.0, float(executable_edge))

            if spread_score is None:
                spread = ctx["spread"] if ctx else None
                spread_score = 0.5 if spread is None else _clamp01(1.0 - (spread / config.MAX_SPREAD))

            liquidity_score = _clamp01(liquidity_score)
            spread_score = _clamp01(spread_score)
            attention_gap_score = _clamp01(attention_gap_score)
            evidence_asymmetry_score = _clamp01(evidence_asymmetry_score)
            stale_price_score = _clamp01(stale_price_score)
            catalyst_score = _clamp01(catalyst_score)
            resolution_clarity_score = _clamp01(resolution_clarity_score)

            total_score = _hidden_gem_score(
                executable_edge=executable_edge,
                liquidity_score=liquidity_score,
                spread_score=spread_score,
                attention_gap_score=attention_gap_score,
                evidence_asymmetry_score=evidence_asymmetry_score,
                stale_price_score=stale_price_score,
                catalyst_score=catalyst_score,
                resolution_clarity_score=resolution_clarity_score,
            )
            if not decision:
                if (total_score >= config.HIDDEN_GEM_DEEP_RESEARCH_SCORE
                        and executable_edge >= config.EDGE_THRESHOLD):
                    decision = "deep_research_candidate"
                elif total_score >= config.HIDDEN_GEM_PRIORITY_SCORE:
                    decision = "watchlist_priority"
                elif total_score >= config.HIDDEN_GEM_WATCHLIST_SCORE:
                    decision = "watchlist"
                else:
                    decision = "reject"

            review_id = db.add_hidden_gem_review(
                conn,
                condition_id=condition_id,
                created_at=None,
                analyst="claude-desktop",
                executable_edge=executable_edge,
                liquidity_score=liquidity_score,
                spread_score=spread_score,
                attention_gap_score=attention_gap_score,
                evidence_asymmetry_score=evidence_asymmetry_score,
                stale_price_score=stale_price_score,
                catalyst_score=catalyst_score,
                resolution_clarity_score=resolution_clarity_score,
                total_score=total_score,
                thesis=thesis.strip(),
                disconfirming_evidence=disconfirming_evidence.strip(),
                next_check_at=next_check_at or None,
                decision=decision,
            )
            conn.commit()
            completeness = _research_completeness(conn, condition_id)

        return {
            "ok": True,
            "review_id": review_id,
            "condition_id": condition_id,
            "question": market["question"],
            "hidden_gem_score": total_score,
            "decision": decision,
            "executable_edge": round(executable_edge, 4),
            "latest_probability_yes": latest_probability,
            "research_completeness": completeness,
        }



    @mcp.tool()
    def hidden_gem_watchlist(limit: int = 20, min_score: float = 40.0) -> dict:
        """Return the latest high-scoring hidden-gem reviews across markets."""
        _ensure_db()
        with db.connect() as conn:
            rows = conn.execute("""
                SELECT h.*, m.question, m.end_date, COALESCE(m.vertical,'unknown') AS vertical
                FROM hidden_gem_reviews h
                JOIN markets m ON m.condition_id = h.condition_id
                JOIN (
                    SELECT condition_id, MAX(created_at) AS latest_at
                    FROM hidden_gem_reviews
                    GROUP BY condition_id
                ) latest
                  ON latest.condition_id = h.condition_id
                 AND latest.latest_at = h.created_at
                WHERE h.total_score >= ?
                  AND COALESCE(h.decision, '') NOT LIKE 'reject%'
                ORDER BY h.total_score DESC, h.created_at DESC
                LIMIT ?
            """, (min_score, limit)).fetchall()
        return {
            "count": len(rows),
            "markets": [{
                "review_id": r["id"],
                "condition_id": r["condition_id"],
                "question": r["question"],
                "vertical": r["vertical"],
                "hidden_gem_score": r["total_score"],
                "decision": r["decision"],
                "executable_edge": r["executable_edge"],
                "attention_gap": r["attention_gap_score"],
                "evidence_asymmetry": r["evidence_asymmetry_score"],
                "stale_price": r["stale_price_score"],
                "catalyst": r["catalyst_score"],
                "end_date": r["end_date"],
                "next_check_at": r["next_check_at"],
                "thesis": r["thesis"],
            } for r in rows],
        }



    @mcp.tool()
    def record_moonshot_review(
        condition_id: str,
        side: str,
        thesis: str,
        kill_criteria: str,
        estimated_probability: float | None = None,
        entry_price: float | None = None,
        catalyst_score: float = 0.5,
        mechanism_score: float = 0.5,
        evidence_score: float = 0.5,
        resolution_score: float = 0.5,
        liquidity_score: float | None = None,
        spread_score: float | None = None,
        narrative_heat_score: float = 0.5,
        anti_random_score: float = 0.5,
        risk_tier: str = "",
        decision: str = "",
        next_research_step: str = "",
        sources: list[str] | None = None,
    ) -> dict:
        """
        First-pass controlled-risk scout for high-payout ideas.

        A moonshot is not a bet recommendation. It is a candidate with asymmetric
        payout, a real mechanism, and a catalyst that deserves deeper research.
        This keeps "enthusiasm" alive while forcing anti-random filters before any
        normal signal process.
        """
        _ensure_db()
        sources = sources or []
        side = side.upper()
        if side not in {"YES", "NO"}:
            return {"error": "side must be YES or NO"}
        if not thesis.strip():
            return {"error": "thesis is required"}
        if not kill_criteria.strip():
            return {"error": "kill_criteria is required"}

        with db.connect() as conn:
            market = conn.execute(
                "SELECT question, vertical, end_date FROM markets WHERE condition_id = ?",
                (condition_id,),
            ).fetchone()
            if not market:
                return {"error": f"market {condition_id} not found"}
            ctx = _latest_execution_context(conn, condition_id)
            if not ctx and entry_price is None:
                return {"error": "no snapshot found; provide entry_price or fetch market first"}

            if entry_price is None:
                entry_price = ctx["yes_entry_price"] if side == "YES" else ctx["no_entry_price"]
            entry_price = float(entry_price)
            if entry_price <= 0 or entry_price >= 1:
                return {"error": "entry_price must be between 0 and 1"}

            implied_probability = entry_price
            payout_multiple = 1.0 / entry_price
            estimated_probability = None if estimated_probability is None else _clamp01(estimated_probability)
            probability_edge = None
            if estimated_probability is not None:
                probability_edge = (
                    estimated_probability - entry_price
                    if side == "YES"
                    else (1.0 - estimated_probability) - entry_price
                )

            if liquidity_score is None:
                liq = float(ctx["liquidity"] or 0.0) if ctx else 0.0
                liquidity_score = _clamp01(liq / config.MOONSHOT_LIQUIDITY_NORM)
            if spread_score is None:
                spread = ctx["spread"] if ctx else None
                spread_score = 0.45 if spread is None else _clamp01(1.0 - (spread / config.MAX_SPREAD))

            catalyst_score = _clamp01(catalyst_score)
            mechanism_score = _clamp01(mechanism_score)
            evidence_score = _clamp01(evidence_score)
            resolution_score = _clamp01(resolution_score)
            liquidity_score = _clamp01(liquidity_score)
            spread_score = _clamp01(spread_score)
            narrative_heat_score = _clamp01(narrative_heat_score)
            anti_random_score = _clamp01(anti_random_score)

            total_score = _moonshot_score(
                probability_edge=probability_edge,
                payout_multiple=payout_multiple,
                catalyst_score=catalyst_score,
                mechanism_score=mechanism_score,
                evidence_score=evidence_score,
                resolution_score=resolution_score,
                liquidity_score=liquidity_score,
                spread_score=spread_score,
                narrative_heat_score=narrative_heat_score,
                anti_random_score=anti_random_score,
            )
            if not risk_tier:
                if entry_price <= config.MOONSHOT_PRICE_MAX:
                    risk_tier = "moonshot"
                elif entry_price <= config.SPECULATIVE_PRICE_MAX:
                    risk_tier = "speculative"
                else:
                    risk_tier = "stretch"
            if not decision:
                if (anti_random_score < config.MOONSHOT_MIN_ANTI_RANDOM
                        or mechanism_score < config.MOONSHOT_MIN_MECHANISM):
                    decision = "reject_random_or_no_mechanism"
                elif total_score >= config.MOONSHOT_PROMOTE_SCORE:
                    decision = "promote_to_deep_research"
                elif total_score >= config.MOONSHOT_PRIORITY_SCORE:
                    decision = "watchlist_priority"
                elif total_score >= config.MOONSHOT_WATCHLIST_SCORE:
                    decision = "watchlist"
                else:
                    decision = "reject"

            review_id = db.add_moonshot_review(
                conn,
                condition_id=condition_id,
                created_at=None,
                analyst="claude-desktop",
                side=side,
                entry_price=entry_price,
                payout_multiple=payout_multiple,
                implied_probability=implied_probability,
                estimated_probability=estimated_probability,
                probability_edge=probability_edge,
                catalyst_score=catalyst_score,
                mechanism_score=mechanism_score,
                evidence_score=evidence_score,
                resolution_score=resolution_score,
                liquidity_score=liquidity_score,
                spread_score=spread_score,
                narrative_heat_score=narrative_heat_score,
                anti_random_score=anti_random_score,
                total_score=total_score,
                risk_tier=risk_tier,
                decision=decision,
                thesis=thesis.strip(),
                kill_criteria=kill_criteria.strip(),
                next_research_step=next_research_step or None,
                sources_json=json.dumps(sources),
            )
            conn.commit()

        return {
            "ok": True,
            "review_id": review_id,
            "condition_id": condition_id,
            "question": market["question"],
            "side": side,
            "entry_price": round(entry_price, 4),
            "payout_multiple": round(payout_multiple, 2),
            "implied_probability": round(implied_probability, 4),
            "estimated_probability": estimated_probability,
            "probability_edge": round(probability_edge, 4) if probability_edge is not None else None,
            "moonshot_score": total_score,
            "risk_tier": risk_tier,
            "decision": decision,
        }



    @mcp.tool()
    def moonshot_watchlist(limit: int = 20, min_score: float = 45.0) -> dict:
        """
        Return latest high-payout candidates that passed the controlled-enthusiasm
        screen and are ready for deeper research.
        """
        _ensure_db()
        with db.connect() as conn:
            rows = conn.execute("""
                SELECT r.*, m.question, m.vertical, m.end_date
                FROM moonshot_reviews r
                JOIN markets m ON m.condition_id = r.condition_id
                JOIN (
                    SELECT condition_id, MAX(created_at) AS latest_at
                    FROM moonshot_reviews
                    GROUP BY condition_id
                ) latest
                  ON latest.condition_id = r.condition_id
                 AND latest.latest_at = r.created_at
                WHERE r.total_score >= ?
                  AND COALESCE(r.decision, '') NOT LIKE 'reject%'
                ORDER BY r.total_score DESC, r.created_at DESC
                LIMIT ?
            """, (min_score, limit)).fetchall()
        return {
            "count": len(rows),
            "markets": [{
                "review_id": r["id"],
                "condition_id": r["condition_id"],
                "question": r["question"],
                "vertical": r["vertical"],
                "side": r["side"],
                "entry_price": r["entry_price"],
                "payout_multiple": round(float(r["payout_multiple"]), 2),
                "estimated_probability": r["estimated_probability"],
                "probability_edge": r["probability_edge"],
                "moonshot_score": r["total_score"],
                "risk_tier": r["risk_tier"],
                "decision": r["decision"],
                "end_date": r["end_date"],
                "thesis": r["thesis"],
                "kill_criteria": r["kill_criteria"],
                "next_research_step": r["next_research_step"],
            } for r in rows],
        }
