"""Auto-generated by Stage 0 splitter. Tools registered by mcp_server.register_all(mcp)."""
from __future__ import annotations
import asyncio
import json
import math
from datetime import datetime, timezone

import httpx

import config
import db
from markets import fetch_active_markets

from lib.execution import (
    clamp01 as _clamp01,
    float_or_none as _float_or_none,
    execution_prices as _execution_prices,
    best_executable_edge as _best_executable_edge,
    no_signal_reason as _no_signal_reason,
)
from lib.queries import (
    latest_probability as _latest_probability,
    latest_execution_context as _latest_execution_context,
    market_row as _market_row,
    research_completeness as _research_completeness,
)
from lib.scoring import (
    hidden_gem_score as _hidden_gem_score,
    moonshot_score as _moonshot_score,
    resolution_completeness as _resolution_completeness,
    pre_bet_score as _pre_bet_score,
    signal_quality_score as _signal_quality_score,
    log_score as _log_score,
    quality_grade as _quality_grade,
    parse_dt as _parse_dt,
    normalize_score_100 as _normalize_score_100,
)
from lib.sizing import recommended_stake as _recommended_stake
from lib.resolution_parser import parse_resolution_clarity as _parse_resolution_clarity


def _today() -> str:
    return datetime.now(timezone.utc).date().isoformat()


def _ensure_db() -> None:
    db.init()


SIGNAL_ARCHETYPES = {
    "countable_catalyst",
    "cheap_optionality",
    "resolution_wording_trap",
    "stale_price",
    "actor_incentive_mismatch",
    "crowd_narrative_error",
    "repricing_watch",
}


def register(mcp):
    @mcp.tool()
    def parse_resolution_clarity(text: str) -> dict:
        """
        Scan resolution text for ambiguous terms (subjective rankings,
        'qualifying', 'consensus', loose quantifiers, multi-condition AND/OR,
        Polymarket-specific wording traps like 'release by X'). Returns
        warnings + ambiguity score 0..1 + an action suggestion.

        Call this on a market description BEFORE drafting record_resolution_map
        so you know which ambiguity_cases to populate. record_resolution_map
        also runs this automatically and includes warnings in its return.
        """
        _ensure_db()
        return _parse_resolution_clarity(text)

    @mcp.tool()
    def record_resolution_map(
        condition_id: str,
        yes_criteria: str,
        no_criteria: str,
        primary_resolution_source: str = "",
        secondary_resolution_sources: str = "",
        deadline_text: str = "",
        ambiguity_cases: str = "",
        non_qualifying_events: str = "",
        required_artifact: str = "",
        resolution_risk_score: float = 0.5,
        wording_trap_score: float = 0.5,
        source_quality_score: float = 0.5,
        deadline_clarity_score: float = 0.5,
        summary: str = "",
    ) -> dict:
        """
        Store the resolution-first map for a market before serious betting.

        This is the hold-to-resolution foundation: what exactly counts as YES,
        what counts as NO, what does not qualify, what source resolves the market,
        and where headlines can mislead the forecast.
        """
        _ensure_db()
        if not yes_criteria.strip() or not no_criteria.strip():
            return {"error": "yes_criteria and no_criteria are required"}

        source_quality_score = _clamp01(source_quality_score)
        deadline_clarity_score = _clamp01(deadline_clarity_score)
        completeness_score = _resolution_completeness(
            yes_criteria=yes_criteria,
            no_criteria=no_criteria,
            primary_resolution_source=primary_resolution_source,
            deadline_text=deadline_text,
            ambiguity_cases=ambiguity_cases,
            non_qualifying_events=non_qualifying_events,
            required_artifact=required_artifact,
            source_quality_score=source_quality_score,
            deadline_clarity_score=deadline_clarity_score,
        )

        with db.connect() as conn:
            market = conn.execute(
                "SELECT question, vertical, end_date FROM markets WHERE condition_id = ?",
                (condition_id,),
            ).fetchone()
            if not market:
                return {"error": f"market {condition_id} not found"}

            # Auto-parse all the resolution text we have and persist ambiguity
            # warnings so future checklists/reviews can inspect the original traps.
            combined_text = " ".join([
                market["question"] or "",
                yes_criteria or "",
                no_criteria or "",
                ambiguity_cases or "",
                non_qualifying_events or "",
                required_artifact or "",
                summary or "",
            ])
            parser_report = _parse_resolution_clarity(combined_text)

            map_id = db.add_resolution_map(
                conn,
                condition_id=condition_id,
                created_at=None,
                analyst="claude-desktop",
                yes_criteria=yes_criteria.strip(),
                no_criteria=no_criteria.strip(),
                primary_resolution_source=primary_resolution_source or None,
                secondary_resolution_sources=secondary_resolution_sources or None,
                deadline_text=deadline_text or market["end_date"],
                ambiguity_cases=ambiguity_cases or None,
                non_qualifying_events=non_qualifying_events or None,
                required_artifact=required_artifact or None,
                resolution_risk_score=_clamp01(resolution_risk_score),
                wording_trap_score=_clamp01(wording_trap_score),
                source_quality_score=source_quality_score,
                deadline_clarity_score=deadline_clarity_score,
                completeness_score=completeness_score,
                parser_warnings_json=json.dumps(parser_report["warnings"]),
                parser_ambiguity_score=parser_report["ambiguity_score"],
                parser_suggestion=parser_report["suggestion"],
                summary=summary or None,
            )
            conn.commit()
        return {
            "ok": True,
            "resolution_map_id": map_id,
            "condition_id": condition_id,
            "question": market["question"],
            "completeness_score": completeness_score,
            "resolution_risk_score": _clamp01(resolution_risk_score),
            "wording_trap_score": _clamp01(wording_trap_score),
            "parser_warnings": parser_report["warnings"],
            "parser_ambiguity_score": parser_report["ambiguity_score"],
            "parser_suggestion": parser_report["suggestion"],
        }



    @mcp.tool()
    def record_pre_bet_checklist(
        condition_id: str,
        intended_side: str,
        estimated_probability: float,
        confidence: float,
        thesis: str,
        top_risks: str,
        disconfirming_evidence: str,
        intended_entry_price: float | None = None,
        sizing_ok: bool = True,
        evidence_balance_ok: bool | None = None,
        resolution_risk_ok: bool | None = None,
        decision: str = "",
        next_action: str = "",
    ) -> dict:
        """
        Gate a potential hold-to-resolution entry before it becomes a signal.

        This checklist pulls from the dossier: resolution map, evidence, actors,
        causal factors, scenarios, premortem, moonshot review, spread/liquidity.
        """
        _ensure_db()
        side = intended_side.upper()
        if side not in {"YES", "NO"}:
            return {"error": "intended_side must be YES or NO"}
        if not thesis.strip() or not top_risks.strip() or not disconfirming_evidence.strip():
            return {"error": "thesis, top_risks, and disconfirming_evidence are required"}
        estimated_probability = _clamp01(estimated_probability)
        confidence = _clamp01(confidence)

        with db.connect() as conn:
            market = conn.execute(
                "SELECT question, vertical, end_date FROM markets WHERE condition_id = ?",
                (condition_id,),
            ).fetchone()
            if not market:
                return {"error": f"market {condition_id} not found"}
            ctx = _latest_execution_context(conn, condition_id)
            if intended_entry_price is None and ctx:
                intended_entry_price = ctx["yes_entry_price"] if side == "YES" else ctx["no_entry_price"]

            edge = None
            if intended_entry_price is not None:
                edge = (
                    estimated_probability - intended_entry_price
                    if side == "YES"
                    else (1.0 - estimated_probability) - intended_entry_price
                )

            counts = {
                "resolution_maps": conn.execute("SELECT COUNT(*) AS n FROM resolution_maps WHERE condition_id = ?", (condition_id,)).fetchone()["n"],
                "evidence": conn.execute("SELECT COUNT(*) AS n FROM evidence WHERE condition_id = ?", (condition_id,)).fetchone()["n"],
                "actors": conn.execute("SELECT COUNT(*) AS n FROM actor_maps WHERE condition_id = ?", (condition_id,)).fetchone()["n"],
                "causal": conn.execute("SELECT COUNT(*) AS n FROM causal_factors WHERE condition_id = ?", (condition_id,)).fetchone()["n"],
                "scenarios": conn.execute("SELECT COUNT(*) AS n FROM scenario_trees WHERE condition_id = ?", (condition_id,)).fetchone()["n"],
                "premortems": conn.execute("SELECT COUNT(*) AS n FROM premortems WHERE condition_id = ?", (condition_id,)).fetchone()["n"],
                "moonshots": conn.execute("SELECT COUNT(*) AS n FROM moonshot_reviews WHERE condition_id = ?", (condition_id,)).fetchone()["n"],
            }
            latest_resolution = conn.execute("""
                SELECT resolution_risk_score, completeness_score
                FROM resolution_maps
                WHERE condition_id = ?
                ORDER BY created_at DESC LIMIT 1
            """, (condition_id,)).fetchone()

            spread_ok = True
            liquidity_ok = True
            if ctx:
                spread_ok = ctx["spread"] is None or ctx["spread"] <= config.MAX_SPREAD
                liquidity_ok = float(ctx["liquidity"] or 0.0) >= 1000.0
            if evidence_balance_ok is None:
                evidence_balance_ok = counts["evidence"] >= 2
            if resolution_risk_ok is None:
                resolution_risk_ok = bool(
                    latest_resolution
                    and _normalize_score_100(latest_resolution["completeness_score"]) >= 70
                    and (latest_resolution["resolution_risk_score"] if latest_resolution["resolution_risk_score"] is not None else 1.0) <= 0.65
                )

            flags = {
                "has_resolution_map": counts["resolution_maps"] > 0,
                "has_evidence_base": counts["evidence"] >= 2,
                "has_actor_map": counts["actors"] > 0,
                "has_causal_model": counts["causal"] > 0,
                "has_scenario_tree": counts["scenarios"] > 0,
                "has_premortem": counts["premortems"] > 0,
                "evidence_balance_ok": bool(evidence_balance_ok),
                "spread_ok": bool(spread_ok),
                "liquidity_ok": bool(liquidity_ok),
                "sizing_ok": bool(sizing_ok),
                "resolution_risk_ok": bool(resolution_risk_ok),
            }
            checklist_score = _pre_bet_score(flags, confidence, edge)
            has_moonshot_review = counts["moonshots"] > 0

            if not decision:
                if not flags["has_resolution_map"]:
                    decision = "block_missing_resolution_map"
                elif not flags["resolution_risk_ok"]:
                    decision = "block_resolution_risk"
                elif checklist_score >= 82 and edge is not None and edge >= config.EDGE_THRESHOLD:
                    decision = "approved_for_signal"
                elif checklist_score >= 82:          # score is high but edge is thin
                    decision = "paper_only_low_edge"
                elif checklist_score >= 68:
                    decision = "needs_more_research"
                else:
                    decision = "reject_incomplete"

            checklist_id = db.add_pre_bet_checklist(
                conn,
                condition_id=condition_id,
                created_at=None,
                analyst="claude-desktop",
                intended_side=side,
                intended_entry_price=intended_entry_price,
                estimated_probability=estimated_probability,
                confidence=confidence,
                edge=edge,
                has_resolution_map=1 if flags["has_resolution_map"] else 0,
                has_evidence_base=1 if flags["has_evidence_base"] else 0,
                has_actor_map=1 if flags["has_actor_map"] else 0,
                has_causal_model=1 if flags["has_causal_model"] else 0,
                has_scenario_tree=1 if flags["has_scenario_tree"] else 0,
                has_premortem=1 if flags["has_premortem"] else 0,
                has_moonshot_review=1 if has_moonshot_review else 0,
                evidence_balance_ok=1 if flags["evidence_balance_ok"] else 0,
                spread_ok=1 if flags["spread_ok"] else 0,
                liquidity_ok=1 if flags["liquidity_ok"] else 0,
                sizing_ok=1 if flags["sizing_ok"] else 0,
                resolution_risk_ok=1 if flags["resolution_risk_ok"] else 0,
                thesis=thesis.strip(),
                top_risks=top_risks.strip(),
                disconfirming_evidence=disconfirming_evidence.strip(),
                checklist_score=checklist_score,
                decision=decision,
                next_action=next_action or None,
            )
            conn.commit()

        return {
            "ok": True,
            "checklist_id": checklist_id,
            "condition_id": condition_id,
            "question": market["question"],
            "intended_side": side,
            "intended_entry_price": intended_entry_price,
            "estimated_probability": estimated_probability,
            "edge": round(edge, 4) if edge is not None else None,
            "checklist_score": checklist_score,
            "decision": decision,
            "flags": {**flags, "has_moonshot_review": has_moonshot_review},
            "counts": counts,
        }



    @mcp.tool()
    def record_outcome_learning_review(
        condition_id: str,
        outcome_side: str,
        outcome_summary: str,
        why_right_or_wrong: str,
        repeatable_lesson: str,
        signal_id: int | None = None,
        analysis_id: int | None = None,
        predicted_side: str = "",
        entry_price: float | None = None,
        probability_yes: float | None = None,
        confidence: float | None = None,
        realized_pnl: float | None = None,
        market_price_at_forecast: float | None = None,
        resolution_error: bool = False,
        probability_error: bool = False,
        evidence_error: bool = False,
        timing_error: bool = False,
        sizing_error: bool = False,
        luck_factor: float = 0.5,
        rule_update: str = "",
    ) -> dict:
        """
        Close the research loop after a market resolves.

        This is not just PnL. It classifies why the signal was right or wrong and
        what rule should change before future hold-to-resolution bets.
        """
        _ensure_db()
        outcome = outcome_side.upper()
        if outcome not in {"YES", "NO"}:
            return {"error": "outcome_side must be YES or NO"}
        if not outcome_summary.strip() or not why_right_or_wrong.strip() or not repeatable_lesson.strip():
            return {"error": "outcome_summary, why_right_or_wrong, and repeatable_lesson are required"}

        with db.connect() as conn:
            market = conn.execute(
                "SELECT question, vertical FROM markets WHERE condition_id = ?",
                (condition_id,),
            ).fetchone()
            if not market:
                return {"error": f"market {condition_id} not found"}
            if signal_id is not None:
                sig = conn.execute("SELECT * FROM signals WHERE id = ?", (signal_id,)).fetchone()
                if sig:
                    predicted_side = predicted_side or sig["side"]
                    entry_price = entry_price if entry_price is not None else float(sig["yes_price_at_signal"])
                    probability_yes = probability_yes if probability_yes is not None else float(sig["claude_prob"])
                    confidence = confidence if confidence is not None else float(sig["confidence"])
                    realized_pnl = realized_pnl if realized_pnl is not None else sig["realized_pnl"]
            if analysis_id is not None:
                analysis = conn.execute("SELECT * FROM analyses WHERE id = ?", (analysis_id,)).fetchone()
                if analysis:
                    probability_yes = probability_yes if probability_yes is not None else float(analysis["probability_yes"])
                    confidence = confidence if confidence is not None else float(analysis["confidence"])
                    market_price_at_forecast = (
                        market_price_at_forecast
                        if market_price_at_forecast is not None
                        else float(analysis["yes_price_at_analysis"])
                    )

            outcome_value = 1.0 if outcome == "YES" else 0.0
            brier_score = None
            market_brier_score = None
            if probability_yes is not None:
                brier_score = (_clamp01(probability_yes) - outcome_value) ** 2
            if market_price_at_forecast is not None:
                market_brier_score = (_clamp01(market_price_at_forecast) - outcome_value) ** 2

            review_id = db.add_outcome_learning_review(
                conn,
                condition_id=condition_id,
                signal_id=signal_id,
                analysis_id=analysis_id,
                created_at=None,
                analyst="claude-desktop",
                outcome_side=outcome,
                predicted_side=predicted_side.upper() if predicted_side else None,
                entry_price=entry_price,
                probability_yes=probability_yes,
                confidence=confidence,
                realized_pnl=realized_pnl,
                brier_score=brier_score,
                market_brier_score=market_brier_score,
                outcome_summary=outcome_summary.strip(),
                why_right_or_wrong=why_right_or_wrong.strip(),
                resolution_error=1 if resolution_error else 0,
                probability_error=1 if probability_error else 0,
                evidence_error=1 if evidence_error else 0,
                timing_error=1 if timing_error else 0,
                sizing_error=1 if sizing_error else 0,
                luck_factor=_clamp01(luck_factor),
                repeatable_lesson=repeatable_lesson.strip(),
                rule_update=rule_update or None,
            )
            conn.commit()

        return {
            "ok": True,
            "outcome_learning_review_id": review_id,
            "condition_id": condition_id,
            "question": market["question"],
            "outcome_side": outcome,
            "predicted_side": predicted_side.upper() if predicted_side else None,
            "brier_score": round(brier_score, 4) if brier_score is not None else None,
            "market_brier_score": round(market_brier_score, 4) if market_brier_score is not None else None,
            "error_tags": {
                "resolution_error": resolution_error,
                "probability_error": probability_error,
                "evidence_error": evidence_error,
                "timing_error": timing_error,
                "sizing_error": sizing_error,
            },
        }



    @mcp.tool()
    def resolution_first_queue(limit: int = 20) -> dict:
        """List active analyzed/signal markets that still lack a resolution map."""
        _ensure_db()
        with db.connect() as conn:
            rows = conn.execute("""
                SELECT DISTINCT m.condition_id, m.question, m.vertical, m.end_date
                FROM markets m
                LEFT JOIN resolution_maps rm ON rm.condition_id = m.condition_id
                WHERE rm.id IS NULL
                  AND (
                    EXISTS (SELECT 1 FROM signals s WHERE s.condition_id = m.condition_id)
                    OR EXISTS (SELECT 1 FROM analyses a WHERE a.condition_id = m.condition_id)
                    OR EXISTS (SELECT 1 FROM moonshot_reviews mo WHERE mo.condition_id = m.condition_id)
                  )
                ORDER BY m.end_date ASC
                LIMIT ?
            """, (limit,)).fetchall()
        return {
            "count": len(rows),
            "markets": [dict(r) for r in rows],
        }


