"""Auto-generated by Stage 0 splitter. Tools registered by mcp_server.register_all(mcp)."""
from __future__ import annotations
import asyncio
import json
import math
from datetime import datetime, timezone

import httpx

import config
import db
from markets import fetch_active_markets, classify_theme_tags

from lib.execution import (
    clamp01 as _clamp01,
    float_or_none as _float_or_none,
    execution_prices as _execution_prices,
    best_executable_edge as _best_executable_edge,
    no_signal_reason as _no_signal_reason,
)
from lib.queries import (
    latest_probability as _latest_probability,
    latest_execution_context as _latest_execution_context,
    market_row as _market_row,
    research_completeness as _research_completeness,
)
from lib.scoring import (
    hidden_gem_score as _hidden_gem_score,
    moonshot_score as _moonshot_score,
    resolution_completeness as _resolution_completeness,
    pre_bet_score as _pre_bet_score,
    signal_quality_score as _signal_quality_score,
    log_score as _log_score,
    quality_grade as _quality_grade,
    parse_dt as _parse_dt,
)
from lib.sizing import recommended_stake as _recommended_stake


def _today() -> str:
    return datetime.now(timezone.utc).date().isoformat()


def _ensure_db() -> None:
    db.init()


SIGNAL_ARCHETYPES = {
    "countable_catalyst",
    "cheap_optionality",
    "resolution_wording_trap",
    "stale_price",
    "actor_incentive_mismatch",
    "crowd_narrative_error",
    "repricing_watch",
}


def register(mcp):
    @mcp.tool()
    async def fetch_candidates(max_markets: int = 30, vertical: str | None = None) -> dict:
        """
        Fetch active Polymarket markets filtered for volume >$10k, 7-180 days to resolution,
        and non-extreme prices. Also records a price snapshot and inserts/updates the market row.

        Args:
            max_markets: cap on how many to return (default 30).
            vertical: optional filter: us_politics, international_geopolitics,
                      tech_business, science_space, or geopolitics alias.
                      If None, returns top markets across ALL verticals.

        Returns markets ranked by volume desc. Each entry includes its 'vertical' tag so you
        can group your research and reasoning. Use a small max_markets per vertical (15-20)
        when running multi-vertical sessions.

        Returns:
            {"date": "YYYY-MM-DD", "vertical": "<name or 'all'>", "count": N,
             "markets": [{condition_id, question, vertical, yes_price, volume,
                           days_to_end, end_date, slug}, ...]}
        """
        _ensure_db()
        async with httpx.AsyncClient() as http:
            markets = await fetch_active_markets(http, vertical=vertical)
        markets = markets[:max_markets]

        out = []
        with db.connect() as conn:
            for m in markets:
                theme_tags = m.theme_tags or classify_theme_tags(m.question)
                db.upsert_market(conn, condition_id=m.condition_id, question=m.question,
                                 slug=m.slug, end_date=m.end_date, vertical=m.vertical)
                db.set_market_tags(conn, condition_id=m.condition_id, tags=theme_tags)
                db.add_snapshot(conn, condition_id=m.condition_id, yes_price=m.yes_price,
                                volume=m.volume, liquidity=m.liquidity,
                                no_price=m.no_price,
                                best_bid=m.best_bid, best_ask=m.best_ask,
                                spread=m.spread,
                                yes_entry_price=m.yes_entry_price,
                                no_entry_price=m.no_entry_price)
                out.append({
                    "condition_id": m.condition_id,
                    "question": m.question,
                    "vertical": m.vertical,
                    "theme_tags": theme_tags,
                    "yes_price": round(m.yes_price, 3),
                    "no_price": round(m.no_price, 3) if m.no_price is not None else None,
                    "yes_entry_price": round(m.yes_entry_price, 3) if m.yes_entry_price is not None else None,
                    "no_entry_price": round(m.no_entry_price, 3) if m.no_entry_price is not None else None,
                    "spread": round(m.spread, 3) if m.spread is not None else None,
                    "volume": round(m.volume, 2),
                    "days_to_end": round(m.days_to_end, 1),
                    "end_date": m.end_date,
                    "slug": m.slug,
                })
            db.start_run(conn, _today())
            conn.commit()

        return {"date": _today(), "vertical": vertical or "all",
                "count": len(out), "markets": out}

    @mcp.tool()
    async def backfill_price_history(condition_id: str, days: int = 30,
                                     fidelity: int = 60) -> dict:
        """
        Pull historical YES prices for a market from Polymarket CLOB and write
        them into ``snapshots`` with ``source='backfill'``. Idempotent - points
        within 12 hours of an existing snapshot are skipped.

        Use this before running discovery_scan if you want stale_price scoring
        to have a real price series instead of a single point. ``interval`` is
        chosen automatically from ``days``: 1d if days >= 14, else 1h.
        """
        from lib.clob import resolve_yes_token, fetch_prices_history, unix_to_iso
        _ensure_db()
        with db.connect() as conn:
            mrow = conn.execute(
                "SELECT question FROM markets WHERE condition_id = ?",
                (condition_id,),
            ).fetchone()
        if not mrow:
            return {"error": f"market {condition_id} not found; call fetch_candidates first"}

        # CLOB `interval` is the time-range covered, not the resolution.
        # max ~= full market history, 1w ~= last week, 1d ~= last 24h, etc.
        if days >= 60:
            interval = "max"
        elif days >= 14:
            interval = "1w"
        elif days >= 3:
            interval = "1d"
        else:
            interval = "6h"
        async with httpx.AsyncClient() as http:
            token = await resolve_yes_token(http, condition_id)
            if not token:
                return {"error": "could not resolve YES token for market"}
            points = await fetch_prices_history(http, token, interval=interval,
                                                 fidelity=fidelity)
        if not points:
            return {"ok": True, "inserted": 0, "skipped": 0,
                    "note": "no history returned by CLOB"}

        inserted = 0
        skipped = 0
        earliest_iso = unix_to_iso(min(pt["t"] for pt in points))
        with db.connect() as conn:
            for pt in points:
                if db.add_snapshot_raw(conn, condition_id=condition_id,
                                       captured_at=unix_to_iso(pt["t"]),
                                       yes_price=pt["p"], source="backfill"):
                    inserted += 1
                else:
                    skipped += 1
            # Roll markets.first_seen_at back to the earliest backfilled point —
            # otherwise stale_price strategy (gate: age > 30d) thinks a 1-year-old
            # Polymarket market is brand new just because we only just learned of it.
            conn.execute("""
                UPDATE markets
                SET first_seen_at = MIN(first_seen_at, ?)
                WHERE condition_id = ?
            """, (earliest_iso, condition_id))
            conn.commit()
        return {
            "ok": True,
            "condition_id": condition_id,
            "question": mrow["question"],
            "interval": interval,
            "points_fetched": len(points),
            "inserted": inserted,
            "skipped": skipped,
        }

    @mcp.tool()
    def daily_run_status(date: str | None = None) -> dict:
        """Check what already happened on a given date (default: today). Use this at session start to avoid double-running."""
        _ensure_db()
        d = date or _today()
        with db.connect() as conn:
            row = conn.execute("SELECT * FROM daily_runs WHERE run_date = ?", (d,)).fetchone()
            if not row:
                return {"date": d, "ran": False}
            sigs = conn.execute("""
                SELECT COUNT(*) AS n FROM signals
                WHERE created_at LIKE ?
            """, (f"{d}%",)).fetchone()
            analyses = conn.execute("""
                SELECT COUNT(*) AS n FROM analyses
                WHERE run_date = ?
            """, (d,)).fetchone()
            evidence = conn.execute("""
                SELECT COUNT(*) AS n FROM evidence
                WHERE created_at LIKE ?
            """, (f"{d}%",)).fetchone()
            reviews = conn.execute("""
                SELECT COUNT(*) AS n FROM hidden_gem_reviews
                WHERE created_at LIKE ?
            """, (f"{d}%",)).fetchone()
            anomalies = conn.execute("""
                SELECT COUNT(*) AS n FROM anomalies
                WHERE created_at LIKE ?
            """, (f"{d}%",)).fetchone()
            scenarios = conn.execute("""
                SELECT COUNT(*) AS n FROM scenario_trees
                WHERE created_at LIKE ?
            """, (f"{d}%",)).fetchone()
            return {
                "date": d,
                "ran": True,
                "started_at": row["started_at"],
                "finished_at": row["finished_at"],
                "markets_seen": row["markets_seen"],
                "sonnet_analyzed": row["sonnet_analyzed"],
                "analyses_recorded": analyses["n"],
                "evidence_recorded": evidence["n"],
                "hidden_gem_reviews": reviews["n"],
                "anomalies_recorded": anomalies["n"],
                "scenarios_recorded": scenarios["n"],
                "signals_emitted_today": sigs["n"],
            }



    @mcp.tool()
    def finalize_daily_run(
        markets_seen: int,
        deep_analyzed: int,
        signals_emitted: int,
        notes: str = "",
    ) -> dict:
        """
        Mark today's run as finished. Call this at the very end of a daily analysis session.

        Args:
            markets_seen: total markets you reviewed
            deep_analyzed: how many you researched with web_search
            signals_emitted: count of signals that fired (you can read this off record_analysis returns)
            notes: free-form note for the run log
        """
        _ensure_db()
        with db.connect() as conn:
            db.finish_run(conn, _today(),
                          markets_seen=markets_seen,
                          haiku_filtered=markets_seen,
                          sonnet_analyzed=deep_analyzed,
                          signals_emitted=signals_emitted,
                          total_cost_usd=0.0)
            conn.commit()
        return {"ok": True, "date": _today(), "notes": notes}



    @mcp.tool()
    def analysis_log(limit: int = 50, decision: str | None = None) -> dict:
        """
        List recent market analyses, including no-signal decisions.

        Args:
            limit: maximum rows to return.
            decision: optional filter: "signal" or "no_signal".
        """
        _ensure_db()
        params: list[object] = []
        where = ""
        if decision:
            where = "WHERE a.decision = ?"
            params.append(decision)
        params.append(limit)
        with db.connect() as conn:
            rows = conn.execute(f"""
                SELECT a.*, m.question, m.end_date, COALESCE(m.vertical,'unknown') AS vertical
                FROM analyses a LEFT JOIN markets m ON m.condition_id = a.condition_id
                {where}
                ORDER BY a.created_at DESC LIMIT ?
            """, params).fetchall()
        out = []
        for r in rows:
            out.append({
                "id": r["id"],
                "date": r["created_at"][:10],
                "decision": r["decision"],
                "no_signal_reason": r["no_signal_reason"],
                "question": r["question"],
                "vertical": r["vertical"],
                "market_price": r["yes_price_at_analysis"],
                "probability_yes": r["probability_yes"],
                "edge": r["edge"],
                "confidence": r["confidence"],
                "signal_id": r["signal_id"],
                "end_date": r["end_date"],
            })
        return {"count": len(out), "analyses": out}



    @mcp.tool()
    def catalyst_calendar(horizon_days: int = 21, limit: int = 40) -> dict:
        """
        Upcoming markets that deserve attention because the resolution window is near.

        This is a hold-to-resolution monitoring calendar, not a trading engine.
        It surfaces open positions, approved/recent analyses, hidden-gem reviews,
        and moonshot reviews whose end date falls inside the horizon.
        """
        _ensure_db()
        horizon_days = max(1, min(int(horizon_days), 90))
        limit = max(1, min(int(limit), 100))
        with db.connect() as conn:
            rows = conn.execute("""
                SELECT m.condition_id, m.question, m.vertical, m.end_date,
                       MAX(s.created_at) AS last_signal_at,
                       MAX(a.created_at) AS last_analysis_at,
                       MAX(h.created_at) AS last_hidden_gem_at,
                       MAX(mo.created_at) AS last_moonshot_at,
                       MAX(p.opened_at) AS position_opened_at,
                       COUNT(DISTINCT p.id) AS open_positions
                FROM markets m
                LEFT JOIN signals s ON s.condition_id = m.condition_id
                LEFT JOIN analyses a ON a.condition_id = m.condition_id
                LEFT JOIN hidden_gem_reviews h ON h.condition_id = m.condition_id
                LEFT JOIN moonshot_reviews mo ON mo.condition_id = m.condition_id
                LEFT JOIN positions p
                  ON p.condition_id = m.condition_id
                 AND p.status IN ('open','filled','partially_filled')
                WHERE m.end_date IS NOT NULL
                  AND m.resolved = 0
                  AND julianday(m.end_date) BETWEEN julianday('now') AND julianday('now', ?)
                  AND (
                    s.id IS NOT NULL OR a.id IS NOT NULL OR h.id IS NOT NULL
                    OR mo.id IS NOT NULL OR p.id IS NOT NULL
                  )
                GROUP BY m.condition_id
                ORDER BY julianday(m.end_date) ASC
                LIMIT ?
            """, (f"+{horizon_days} days", limit)).fetchall()
            items = []
            now = datetime.now(timezone.utc)
            for r in rows:
                try:
                    end_dt = datetime.fromisoformat(r["end_date"].replace("Z", "+00:00"))
                    days_to_end = (end_dt - now).total_seconds() / 86400
                except Exception:
                    days_to_end = None
                reasons = []
                if r["open_positions"]:
                    reasons.append("open_position")
                if r["last_hidden_gem_at"]:
                    reasons.append("hidden_gem_watch")
                if r["last_moonshot_at"]:
                    reasons.append("moonshot_watch")
                if r["last_analysis_at"] and not r["last_signal_at"]:
                    reasons.append("analyzed_no_position")
                items.append({
                    "condition_id": r["condition_id"],
                    "question": r["question"],
                    "vertical": r["vertical"],
                    "theme_tags": db.get_market_tags(conn, r["condition_id"]),
                    "end_date": r["end_date"],
                    "days_to_end": round(days_to_end, 1) if days_to_end is not None else None,
                    "reasons": reasons,
                    "last_touch": max(x for x in [
                        r["last_signal_at"], r["last_analysis_at"],
                        r["last_hidden_gem_at"], r["last_moonshot_at"],
                        r["position_opened_at"],
                    ] if x is not None),
                })
        return {"horizon_days": horizon_days, "count": len(items), "markets": items}


    @mcp.tool()
    def due_for_recheck(limit: int = 30) -> dict:
        """
        Markets that need a fresh research pass.

        Sources:
        - hidden-gem reviews whose next_check_at is due;
        - moonshot reviews with a next_research_step;
        - open positions without an analysis/forecast update in the last 72h.
        """
        _ensure_db()
        limit = max(1, min(int(limit), 100))
        with db.connect() as conn:
            due_hidden = conn.execute("""
                SELECT h.condition_id, m.question, m.vertical, m.end_date,
                       h.next_check_at, h.total_score, h.decision, h.thesis
                FROM hidden_gem_reviews h
                JOIN markets m ON m.condition_id = h.condition_id
                JOIN (
                    SELECT condition_id, MAX(created_at) AS latest_at
                    FROM hidden_gem_reviews GROUP BY condition_id
                ) latest
                  ON latest.condition_id = h.condition_id
                 AND latest.latest_at = h.created_at
                WHERE h.next_check_at IS NOT NULL
                  AND julianday(h.next_check_at) <= julianday('now')
                ORDER BY h.next_check_at ASC
                LIMIT ?
            """, (limit,)).fetchall()
            due_moon = conn.execute("""
                SELECT mo.condition_id, m.question, m.vertical, m.end_date,
                       mo.created_at, mo.total_score, mo.decision,
                       mo.next_research_step, mo.thesis
                FROM moonshot_reviews mo
                JOIN markets m ON m.condition_id = mo.condition_id
                JOIN (
                    SELECT condition_id, MAX(created_at) AS latest_at
                    FROM moonshot_reviews GROUP BY condition_id
                ) latest
                  ON latest.condition_id = mo.condition_id
                 AND latest.latest_at = mo.created_at
                WHERE mo.next_research_step IS NOT NULL
                  AND mo.decision NOT LIKE 'reject%'
                ORDER BY mo.total_score DESC, mo.created_at ASC
                LIMIT ?
            """, (limit,)).fetchall()
            stale_positions = conn.execute("""
                SELECT p.condition_id, m.question, m.vertical, m.end_date,
                       p.opened_at, p.intended_side, p.intended_stake_usd,
                       MAX(a.created_at) AS last_analysis_at,
                       MAX(fu.created_at) AS last_update_at
                FROM positions p
                JOIN markets m ON m.condition_id = p.condition_id
                LEFT JOIN analyses a ON a.condition_id = p.condition_id
                LEFT JOIN forecast_updates fu ON fu.condition_id = p.condition_id
                WHERE p.status IN ('open','filled','partially_filled')
                GROUP BY p.condition_id
                HAVING julianday(COALESCE(MAX(fu.created_at), MAX(a.created_at), p.opened_at)) <= julianday('now', '-72 hours')
                ORDER BY julianday(COALESCE(MAX(fu.created_at), MAX(a.created_at), p.opened_at)) ASC
                LIMIT ?
            """, (limit,)).fetchall()
            items = []
            seen = set()
            for r in due_hidden:
                seen.add(r["condition_id"])
                items.append({
                    "kind": "hidden_gem_recheck",
                    "condition_id": r["condition_id"],
                    "question": r["question"],
                    "vertical": r["vertical"],
                    "theme_tags": db.get_market_tags(conn, r["condition_id"]),
                    "end_date": r["end_date"],
                    "due_at": r["next_check_at"],
                    "score": r["total_score"],
                    "decision": r["decision"],
                    "why": r["thesis"],
                })
            for r in due_moon:
                if r["condition_id"] in seen:
                    continue
                seen.add(r["condition_id"])
                items.append({
                    "kind": "moonshot_next_step",
                    "condition_id": r["condition_id"],
                    "question": r["question"],
                    "vertical": r["vertical"],
                    "theme_tags": db.get_market_tags(conn, r["condition_id"]),
                    "end_date": r["end_date"],
                    "score": r["total_score"],
                    "decision": r["decision"],
                    "why": r["next_research_step"],
                })
            for r in stale_positions:
                if r["condition_id"] in seen:
                    continue
                seen.add(r["condition_id"])
                items.append({
                    "kind": "stale_open_position",
                    "condition_id": r["condition_id"],
                    "question": r["question"],
                    "vertical": r["vertical"],
                    "theme_tags": db.get_market_tags(conn, r["condition_id"]),
                    "end_date": r["end_date"],
                    "side": r["intended_side"],
                    "stake_usd": r["intended_stake_usd"],
                    "why": "open position has no analysis or forecast update in the last 72h",
                })
        return {"count": min(len(items), limit), "items": items[:limit]}


    @mcp.tool()
    def daily_research_brief(horizon_days: int = 7, discovery_limit: int = 10) -> dict:
        """
        One-call Aladdin start panel for a research session.

        This is intentionally DB-first and non-trading: it shows portfolio risk,
        near catalysts, due rechecks, recent discovery candidates, incomplete
        dossiers, and pending outcome reviews. Run discovery_scan separately when
        you want fresh network discovery.
        """
        _ensure_db()
        horizon_days = max(1, min(int(horizon_days), 30))
        discovery_limit = max(1, min(int(discovery_limit), 30))
        with db.connect() as conn:
            from lib.exposure import open_exposure
            exposure = open_exposure(conn)
            open_positions = conn.execute("""
                SELECT COUNT(*) AS n FROM positions
                WHERE status IN ('open','filled','partially_filled')
            """).fetchone()["n"]
            pending_outcomes = conn.execute("""
                SELECT COUNT(*) AS n
                FROM positions p
                JOIN markets m ON m.condition_id = p.condition_id
                LEFT JOIN outcome_learning_reviews olr ON olr.condition_id = p.condition_id
                WHERE m.resolved = 1 AND olr.id IS NULL
            """).fetchone()["n"]
            discovery_rows = conn.execute("""
                SELECT m.condition_id, m.question, m.vertical, m.end_date,
                       s.captured_at, s.yes_price, s.spread, s.volume, s.liquidity
                FROM snapshots s
                JOIN markets m ON m.condition_id = s.condition_id
                JOIN (
                    SELECT condition_id, MAX(captured_at) AS latest_at
                    FROM snapshots WHERE source = 'discovery'
                    GROUP BY condition_id
                ) latest
                  ON latest.condition_id = s.condition_id
                 AND latest.latest_at = s.captured_at
                LEFT JOIN positions p
                  ON p.condition_id = m.condition_id
                 AND p.status IN ('open','filled','partially_filled')
                WHERE p.id IS NULL
                ORDER BY s.captured_at DESC
                LIMIT ?
            """, (discovery_limit,)).fetchall()
            incomplete_rows = conn.execute("""
                SELECT m.condition_id, m.question, m.vertical, m.end_date,
                       MAX(COALESCE(a.created_at, h.created_at, mo.created_at, m.last_seen_at)) AS last_touch
                FROM markets m
                LEFT JOIN analyses a ON a.condition_id = m.condition_id
                LEFT JOIN hidden_gem_reviews h ON h.condition_id = m.condition_id
                LEFT JOIN moonshot_reviews mo ON mo.condition_id = m.condition_id
                WHERE a.id IS NOT NULL OR h.id IS NOT NULL OR mo.id IS NOT NULL
                GROUP BY m.condition_id
                ORDER BY last_touch DESC
                LIMIT 50
            """).fetchall()
            incomplete = []
            for r in incomplete_rows:
                comp = _research_completeness(conn, r["condition_id"])
                if comp["score"] < 85:
                    incomplete.append({
                        "condition_id": r["condition_id"],
                        "question": r["question"],
                        "vertical": r["vertical"],
                        "theme_tags": db.get_market_tags(conn, r["condition_id"]),
                        "score": comp["score"],
                        "missing": comp["missing"],
                    })
                if len(incomplete) >= 10:
                    break
            recent_discovery = [{
                "condition_id": r["condition_id"],
                "question": r["question"],
                "vertical": r["vertical"],
                "theme_tags": db.get_market_tags(conn, r["condition_id"]),
                "end_date": r["end_date"],
                "captured_at": r["captured_at"],
                "yes_price": r["yes_price"],
                "spread": r["spread"],
                "volume": r["volume"],
                "liquidity": r["liquidity"],
            } for r in discovery_rows]
        return {
            "date": _today(),
            "portfolio": {
                "open_positions": open_positions,
                "total_at_risk_usd": exposure["total_at_risk_usd"],
                "by_vertical": exposure["by_vertical"],
                "by_theme": exposure["by_theme"],
                "by_deadline_week": exposure["by_deadline_week"],
            },
            "catalysts": catalyst_calendar(horizon_days=horizon_days, limit=20),
            "due_for_recheck": due_for_recheck(limit=20),
            "recent_discovery_candidates": recent_discovery,
            "incomplete_research": incomplete,
            "pending_outcome_reviews": pending_outcomes,
            "recommended_next_calls": [
                "portfolio_snapshot",
                "discovery_scan",
                "backfill_price_history for top discovery candidates",
                "record_pre_bet_checklist only after dossier is complete",
            ],
        }


    @mcp.tool()
    def performance_report() -> dict:
        """Summary: cumulative signal count, win-rate, PnL, ROI."""
        _ensure_db()
        with db.connect() as conn:
            analyses = conn.execute("SELECT COUNT(*) AS n FROM analyses").fetchone()["n"]
            evidence = conn.execute("SELECT COUNT(*) AS n FROM evidence").fetchone()["n"]
            forecast_updates = conn.execute("SELECT COUNT(*) AS n FROM forecast_updates").fetchone()["n"]
            hidden_reviews = conn.execute("SELECT COUNT(*) AS n FROM hidden_gem_reviews").fetchone()["n"]
            actors = conn.execute("SELECT COUNT(*) AS n FROM actor_maps").fetchone()["n"]
            causal_factors = conn.execute("SELECT COUNT(*) AS n FROM causal_factors").fetchone()["n"]
            anomalies = conn.execute("SELECT COUNT(*) AS n FROM anomalies").fetchone()["n"]
            scenarios = conn.execute("SELECT COUNT(*) AS n FROM scenario_trees").fetchone()["n"]
            premortems = conn.execute("SELECT COUNT(*) AS n FROM premortems").fetchone()["n"]
            signal_quality = conn.execute("SELECT COUNT(*) AS n FROM signal_quality_reviews").fetchone()["n"]
            archetypes = conn.execute("SELECT COUNT(*) AS n FROM signal_archetype_reviews").fetchone()["n"]
            benchmarks = conn.execute("SELECT COUNT(*) AS n FROM signal_benchmark_cases").fetchone()["n"]
            moonshots = conn.execute("SELECT COUNT(*) AS n FROM moonshot_reviews").fetchone()["n"]
            resolution_maps = conn.execute("SELECT COUNT(*) AS n FROM resolution_maps").fetchone()["n"]
            pre_bet = conn.execute("SELECT COUNT(*) AS n FROM pre_bet_checklists").fetchone()["n"]
            outcome_learning = conn.execute("SELECT COUNT(*) AS n FROM outcome_learning_reviews").fetchone()["n"]
            total = conn.execute("SELECT COUNT(*) AS n FROM signals").fetchone()["n"]
            closed_rows = conn.execute("""
                SELECT realized_pnl, bet_amount, side FROM signals WHERE resolved = 1
            """).fetchall()
            open_n = conn.execute(
                "SELECT COUNT(*) AS n FROM signals WHERE resolved = 0"
            ).fetchone()["n"]
            runs = conn.execute("SELECT COUNT(*) AS n FROM daily_runs WHERE finished_at IS NOT NULL").fetchone()["n"]

        closed_n = len(closed_rows)
        wins = sum(1 for r in closed_rows if (r["realized_pnl"] or 0) > 0)
        pnl = sum(r["realized_pnl"] or 0 for r in closed_rows)
        bet_total = sum(r["bet_amount"] for r in closed_rows) or 1.0
        return {
            "total_signals": total,
            "total_analyses": analyses,
            "total_evidence_items": evidence,
            "total_forecast_updates": forecast_updates,
            "total_hidden_gem_reviews": hidden_reviews,
            "total_actors": actors,
            "total_causal_factors": causal_factors,
            "total_anomalies": anomalies,
            "total_scenarios": scenarios,
            "total_premortems": premortems,
            "total_signal_quality_reviews": signal_quality,
            "total_signal_archetype_reviews": archetypes,
            "total_signal_benchmark_cases": benchmarks,
            "total_moonshot_reviews": moonshots,
            "total_resolution_maps": resolution_maps,
            "total_pre_bet_checklists": pre_bet,
            "total_outcome_learning_reviews": outcome_learning,
            "signal_rate_pct": round(total / analyses * 100, 1) if analyses else None,
            "open": open_n,
            "closed": closed_n,
            "wins": wins,
            "win_rate_pct": round(wins / closed_n * 100, 1) if closed_n else None,
            "pnl_usd": round(pnl, 2),
            "roi_pct": round(pnl / bet_total * 100, 1) if closed_n else None,
            "daily_runs_completed": runs,
        }


    if __name__ == "__main__":
        mcp.run()
