"""Auto-generated by Stage 0 splitter. Tools registered by mcp_server.register_all(mcp)."""
from __future__ import annotations
import asyncio
import json
import math
from datetime import datetime, timezone

import httpx

import config
import db
from markets import fetch_active_markets

from lib.execution import (
    clamp01 as _clamp01,
    float_or_none as _float_or_none,
    execution_prices as _execution_prices,
    best_executable_edge as _best_executable_edge,
    no_signal_reason as _no_signal_reason,
)
from lib.queries import (
    latest_probability as _latest_probability,
    latest_execution_context as _latest_execution_context,
    market_row as _market_row,
    research_completeness as _research_completeness,
)
from lib.scoring import (
    hidden_gem_score as _hidden_gem_score,
    moonshot_score as _moonshot_score,
    resolution_completeness as _resolution_completeness,
    pre_bet_score as _pre_bet_score,
    signal_quality_score as _signal_quality_score,
    log_score as _log_score,
    quality_grade as _quality_grade,
    parse_dt as _parse_dt,
)
from lib.sizing import recommended_stake as _recommended_stake
from lib.pnl import realized_pnl as _realized_pnl


def _today() -> str:
    return datetime.now(timezone.utc).date().isoformat()


def _ensure_db() -> None:
    db.init()


SIGNAL_ARCHETYPES = {
    "countable_catalyst",
    "cheap_optionality",
    "resolution_wording_trap",
    "stale_price",
    "actor_incentive_mismatch",
    "crowd_narrative_error",
    "repricing_watch",
}


def register(mcp):
    @mcp.tool()
    async def get_market_details(condition_id: str) -> dict:
        """
        Fetch the full market record from Gamma API including resolution criteria,
        description, current orderbook stats (bid/ask/spread), and liquidity.

        Use this during DEEP research (Phase 2) to verify exact resolution rules before
        placing a high-conviction signal. Many "edge" opportunities turn out to be
        misreads of resolution criteria.

        Returns:
            {"question", "description", "resolution_source", "yes_price", "no_price",
             "spread", "best_bid", "best_ask", "volume", "liquidity", "end_date",
             "tags", "url"}
        """
        GAMMA = "https://gamma-api.polymarket.com"
        async with httpx.AsyncClient(timeout=20) as http:
            r = await http.get(f"{GAMMA}/markets", params={"condition_ids": condition_id})
            r.raise_for_status()
            data = r.json()
            items = data if isinstance(data, list) else data.get("data", [])
            if not items:
                return {"error": f"market {condition_id} not found"}
            m = items[0]

        prices = m.get("outcomePrices")
        if isinstance(prices, str):
            try:
                prices = json.loads(prices)
            except Exception:
                prices = []
        yes_p = float(prices[0]) if prices and len(prices) >= 2 else None
        no_p = float(prices[1]) if prices and len(prices) >= 2 else None
        best_bid = _float_or_none(m.get("bestBid"))
        best_ask = _float_or_none(m.get("bestAsk"))
        spread = _float_or_none(m.get("spread"))
        yes_entry = None
        no_entry = None
        if yes_p is not None and no_p is not None:
            yes_entry, no_entry, spread = _execution_prices(yes_p, no_p, best_bid, best_ask, spread)

        return {
            "question": m.get("question"),
            "description": m.get("description"),  # ← resolution criteria usually live here
            "resolution_source": m.get("resolutionSource"),
            "slug": m.get("slug"),
            "url": f"https://polymarket.com/event/{m.get('slug')}" if m.get("slug") else None,
            "yes_price": yes_p,
            "no_price": no_p,
            "best_bid": best_bid,
            "best_ask": best_ask,
            "spread": spread,
            "yes_entry_price": yes_entry,
            "no_entry_price": no_entry,
            "volume": m.get("volumeNum") or m.get("volume"),
            "liquidity": m.get("liquidityNum") or m.get("liquidity"),
            "end_date": m.get("endDate"),
            "active": m.get("active"),
            "closed": m.get("closed"),
            "tags": [t.get("label") if isinstance(t, dict) else t for t in (m.get("tags") or [])],
        }



    @mcp.tool()
    def mark_live_position(
        signal_id: int,
        real_entry_price: float,
        real_bet_usd: float,
        real_shares: float | None = None,
        notes: str = "",
    ) -> dict:
        """
        Mark an existing paper signal as having been placed with real money.
        Use this when user actually deposits a bet on Polymarket based on a signal.

        Args:
            signal_id: the paper signal ID (from open_signals or record_analysis output)
            real_entry_price: actual fill price on Polymarket (may differ from signal price due to spread/slippage)
            real_bet_usd: actual USD amount put down
            real_shares: number of shares purchased (USD / entry_price, computed if not provided)
            notes: free-form note

        Returns:
            Updated position info with computed max_payout
        """
        _ensure_db()
        if real_shares is None:
            real_shares = round(real_bet_usd / real_entry_price, 4)
        max_payout = real_shares  # each share pays $1 if YES wins (or NO wins for NO side)

        with db.connect() as conn:
            row = conn.execute(
                "SELECT side, condition_id FROM signals WHERE id = ?", (signal_id,)
            ).fetchone()
            if not row:
                return {"error": f"signal {signal_id} not found"}

            now = db.utcnow_iso()
            conn.execute("""
                UPDATE signals SET
                    real_money = 1,
                    real_entry_price = ?,
                    real_bet_usd = ?,
                    real_shares = ?,
                    real_filled_at = ?,
                    real_max_payout = ?
                WHERE id = ?
            """, (real_entry_price, real_bet_usd, real_shares, now, max_payout, signal_id))
            conn.commit()
            return {
                "ok": True,
                "signal_id": signal_id,
                "side": row["side"],
                "real_entry_price": real_entry_price,
                "real_bet_usd": real_bet_usd,
                "real_shares": real_shares,
                "max_payout": max_payout,
                "potential_profit": round(max_payout - real_bet_usd, 2),
                "potential_roi_pct": round((max_payout / real_bet_usd - 1) * 100, 1),
                "notes": notes,
            }



    @mcp.tool()
    async def record_live_position(
        condition_id: str,
        side: str,
        real_entry_price: float,
        real_bet_usd: float,
        claude_prob: float,
        confidence: float,
        reasoning: str,
        sources: list[str] | None = None,
    ) -> dict:
        """
        Create a NEW signal AND mark it as real money — for positions taken without
        a prior paper signal. Fetches current market state to lock the snapshot.

        Args:
            condition_id: Polymarket market condition ID
            side: "YES" or "NO"
            real_entry_price: actual fill price (between 0 and 1)
            real_bet_usd: amount staked
            claude_prob: your calibrated probability estimate
            confidence: 0.0-1.0
            reasoning: why you took this bet
            sources: URLs/citations
        """
        _ensure_db()
        sources = sources or []
        side = side.upper()
        if side not in ("YES", "NO"):
            return {"error": "side must be YES or NO"}

        # Fetch current market state for the snapshot
        details = await get_market_details(condition_id)
        if "error" in details:
            return details
        market_yes = details.get("yes_price") or 0.5

        if side == "YES":
            edge = float(claude_prob) - real_entry_price
            yes_equivalent_entry = real_entry_price
        else:
            edge = (1.0 - float(claude_prob)) - real_entry_price
            yes_equivalent_entry = 1.0 - real_entry_price
        side_entry_price = real_entry_price
        edge = max(edge, 0.0)
        real_shares = round(real_bet_usd / real_entry_price, 4)

        with db.connect() as conn:
            # Ensure market exists in DB
            db.upsert_market(
                conn,
                condition_id=condition_id,
                question=details.get("question") or "",
                slug=details.get("slug"),
                end_date=details.get("end_date"),
                vertical="unknown",  # will be tagged on next fetch_candidates
            )
            db.add_snapshot(
                conn,
                condition_id=condition_id,
                yes_price=market_yes,
                volume=details.get("volume"),
                liquidity=details.get("liquidity"),
                no_price=details.get("no_price"),
                best_bid=details.get("best_bid"),
                best_ask=details.get("best_ask"),
                spread=details.get("spread"),
                yes_entry_price=details.get("yes_entry_price"),
                no_entry_price=details.get("no_entry_price"),
            )
            signal_id = db.add_signal(
                conn,
                condition_id=condition_id,
                created_at=None,
                model="claude-desktop-live",
                yes_price_at_signal=yes_equivalent_entry,
                yes_equivalent_entry=yes_equivalent_entry,
                side_entry_price=side_entry_price,
                claude_prob=claude_prob,
                confidence=confidence,
                side=side,
                edge=edge,
                bet_amount=real_bet_usd,
                reasoning=reasoning,
                sources_json=json.dumps(sources),
                tokens_in=None,
                tokens_out=None,
                cache_read_tokens=None,
                cost_usd=0.0,
                gate_status="manual",
                gate_audit_note="operator live position, not formal signal gate",
            )
            analysis_id = db.add_analysis(
                conn,
                run_date=_today(),
                condition_id=condition_id,
                created_at=None,
                analyst="claude-desktop",
                model="claude-desktop-live",
                yes_price_at_analysis=market_yes,
                probability_yes=max(0.0, min(1.0, float(claude_prob))),
                confidence=max(0.0, min(1.0, float(confidence))),
                edge=edge,
                decision="live_position",
                no_signal_reason=None,
                signal_id=signal_id,
                reasoning=reasoning,
                sources_json=json.dumps(sources),
                notes="Created directly from record_live_position",
            )
            now = db.utcnow_iso()
            conn.execute("""
                UPDATE signals SET
                    real_money = 1,
                    real_entry_price = ?,
                    real_bet_usd = ?,
                    real_shares = ?,
                    real_filled_at = ?,
                    real_max_payout = ?
                WHERE id = ?
            """, (real_entry_price, real_bet_usd, real_shares, now, real_shares, signal_id))
            conn.commit()

        return {
            "ok": True,
            "analysis_id": analysis_id,
            "signal_id": signal_id,
            "side": side,
            "real_entry_price": real_entry_price,
            "real_bet_usd": real_bet_usd,
            "real_shares": real_shares,
            "max_payout": real_shares,
            "potential_profit": round(real_shares - real_bet_usd, 2),
            "potential_roi_pct": round((real_shares / real_bet_usd - 1) * 100, 1),
        }

    @mcp.tool()
    def record_real_manual_trade(
        condition_id: str,
        side: str,
        entry_price: float,
        stake_usd: float,
        shares: float | None = None,
        filled_at: str = "",
        thesis: str = "",
        sources: list[str] | None = None,
        probability_yes: float | None = None,
        confidence: float = 0.0,
        question: str = "",
        slug: str = "",
        end_date: str = "",
        primary_archetype: str | None = None,
        exit_price: float | None = None,
        exit_shares: float | None = None,
        exited_at: str = "",
        closed_reason: str = "",
    ) -> dict:
        """
        Legal path for operator-entered real Polymarket trades.

        This records the real fill honestly as manual/retrospective. It does not
        pretend a prior approved pre-bet checklist existed and it marks the
        signal row with manual_trade=1/retrospective=1 so ledger can distinguish
        it from a gate violation.
        """
        _ensure_db()
        side = side.upper().strip()
        if side not in {"YES", "NO"}:
            return {"error": "side must be YES or NO"}
        if not (0 < float(entry_price) < 1):
            return {"error": "entry_price must be between 0 and 1"}
        if float(stake_usd) <= 0:
            return {"error": "stake_usd must be positive"}
        sources = sources or []
        entry_price = float(entry_price)
        stake_usd = float(stake_usd)
        shares = float(shares) if shares is not None else round(stake_usd / entry_price, 4)
        filled_at = filled_at or db.utcnow_iso()
        confidence = max(0.0, min(1.0, float(confidence or 0.0)))
        if probability_yes is None:
            probability_yes = entry_price if side == "YES" else 1.0 - entry_price
        probability_yes = max(0.0, min(1.0, float(probability_yes)))
        yes_equivalent_entry = entry_price if side == "YES" else 1.0 - entry_price
        edge = probability_yes - yes_equivalent_entry if side == "YES" else (1.0 - probability_yes) - entry_price
        edge = round(edge, 6)
        thesis = thesis.strip() or "Manual real-money trade recorded retrospectively by operator."

        with db.connect() as conn:
            market = conn.execute("SELECT * FROM markets WHERE condition_id = ?", (condition_id,)).fetchone()
            if market is None:
                if not question.strip():
                    return {"error": "market_not_found", "next_action": "provide question/slug/end_date or fetch market first"}
                db.upsert_market(
                    conn,
                    condition_id=condition_id,
                    question=question.strip(),
                    slug=slug or None,
                    end_date=end_date or None,
                    vertical="unknown",
                )
                market = conn.execute("SELECT * FROM markets WHERE condition_id = ?", (condition_id,)).fetchone()
            signal_id = db.add_signal(
                conn,
                condition_id=condition_id,
                created_at=filled_at,
                model="manual-operator-trade",
                yes_price_at_signal=yes_equivalent_entry,
                yes_equivalent_entry=yes_equivalent_entry,
                side_entry_price=entry_price,
                claude_prob=probability_yes,
                confidence=confidence,
                side=side,
                edge=edge,
                bet_amount=stake_usd,
                reasoning=thesis,
                sources_json=json.dumps(sources),
                tokens_in=None,
                tokens_out=None,
                cache_read_tokens=None,
                cost_usd=0.0,
                gate_status="manual",
                gate_audit_note="manual/operator real trade, not formal signal gate",
            )
            conn.execute("""
                UPDATE signals SET
                    real_money = 1,
                    real_entry_price = ?,
                    real_bet_usd = ?,
                    real_shares = ?,
                    real_filled_at = ?,
                    real_max_payout = ?,
                    manual_trade = 1,
                    retrospective = 1,
                    operator_decision = 'manual_real_trade'
                WHERE id = ?
            """, (entry_price, stake_usd, shares, filled_at, shares, signal_id))
            analysis_id = db.add_analysis(
                conn,
                run_date=_today(),
                condition_id=condition_id,
                created_at=filled_at,
                analyst="operator-manual",
                model="manual-operator-trade",
                yes_price_at_analysis=yes_equivalent_entry,
                probability_yes=probability_yes,
                confidence=confidence,
                edge=edge,
                decision="manual_real_trade",
                no_signal_reason="retrospective_operator_entry_no_prebet_gate",
                signal_id=signal_id,
                reasoning=thesis,
                sources_json=json.dumps(sources),
                notes="Recorded through record_real_manual_trade; not a formal pre-bet Signal commit.",
            )
            is_closed = exit_price is not None
            position_id = db.add_position(
                conn,
                condition_id=condition_id,
                signal_id=signal_id,
                opened_at=filled_at,
                intended_side=side,
                intended_entry_price=entry_price,
                side_entry_price=entry_price,
                yes_equivalent_entry=yes_equivalent_entry,
                intended_stake_usd=stake_usd,
                stake_source="real",
                status="closed" if is_closed else "open",
                thesis_snapshot_text=thesis,
                primary_archetype=primary_archetype,
                end_date=(market["end_date"] if market else None),
            )
            entry_fill_id = db.add_fill(
                conn,
                position_id=position_id,
                side=side,
                price=entry_price,
                shares=shares,
                stake_usd=stake_usd,
                venue="polymarket",
                slippage_vs_intent=0.0,
                filled_at=filled_at,
            )
            exit_fill_id = None
            realized = None
            if is_closed:
                exit_price = float(exit_price)
                if not (0 <= exit_price <= 1):
                    return {"error": "exit_price must be between 0 and 1"}
                exit_shares = float(exit_shares) if exit_shares is not None else shares
                exited_at = exited_at or db.utcnow_iso()
                exit_value = exit_price * exit_shares
                realized = round(exit_value - stake_usd * (exit_shares / shares if shares else 1.0), 2)
                exit_fill_id = db.add_fill(
                    conn,
                    position_id=position_id,
                    side=f"SELL_{side}",
                    price=exit_price,
                    shares=exit_shares,
                    stake_usd=exit_value,
                    venue="polymarket",
                    slippage_vs_intent=0.0,
                    filled_at=exited_at,
                )
                conn.execute(
                    "UPDATE positions SET closed_at = ?, closed_reason = ? WHERE id = ?",
                    (exited_at, closed_reason or "manual exit recorded", position_id),
                )
                conn.execute(
                    "UPDATE signals SET real_pnl_actual = ?, realized_pnl = ? WHERE id = ?",
                    (realized, realized, signal_id),
                )
                db.add_pnl_event(
                    conn,
                    position_id=position_id,
                    event_type="partial_exit",
                    value_usd=round(exit_value, 2),
                    delta_pnl_usd=realized,
                    note=closed_reason or "manual exit recorded",
                    event_at=exited_at,
                )
            conn.commit()

        return {
            "ok": True,
            "recorded": True,
            "workflow": "record_real_manual_trade",
            "manual_trade": True,
            "retrospective": True,
            "signal_id": signal_id,
            "analysis_id": analysis_id,
            "position_id": position_id,
            "entry_fill_id": entry_fill_id,
            "exit_fill_id": exit_fill_id,
            "side": side,
            "entry_price": entry_price,
            "stake_usd": stake_usd,
            "shares": shares,
            "max_payout": shares,
            "realized_pnl": realized,
            "status": "closed" if is_closed else "open",
            "note": "Manual real trade recorded honestly; no prior pre-bet approval was invented.",
        }


    @mcp.tool()
    def live_positions_summary() -> dict:
        """Summary of all real-money positions: open, closed, total at risk, total potential."""
        _ensure_db()
        with db.connect() as conn:
            rows = conn.execute("""
                SELECT s.*, m.question, m.end_date, m.resolved AS m_resolved, m.resolved_yes
                FROM signals s LEFT JOIN markets m ON m.condition_id = s.condition_id
                WHERE s.real_money = 1
                ORDER BY s.real_filled_at DESC
            """).fetchall()
        positions = []
        total_at_risk = 0.0
        total_potential = 0.0
        open_count = 0
        closed_count = 0
        total_realized_pnl = 0.0
        for r in rows:
            pos = {
                "signal_id": r["id"],
                "question": r["question"],
                "side": r["side"],
                "entry": r["real_entry_price"],
                "bet_usd": r["real_bet_usd"],
                "shares": r["real_shares"],
                "max_payout": r["real_max_payout"],
                "end_date": (r["end_date"] or "")[:10],
                "resolved": bool(r["resolved"]),
                "realized_pnl": r["real_pnl_actual"],
            }
            positions.append(pos)
            if r["resolved"]:
                closed_count += 1
                total_realized_pnl += r["real_pnl_actual"] or 0
            else:
                open_count += 1
                total_at_risk += r["real_bet_usd"] or 0
                total_potential += r["real_max_payout"] or 0
        return {
            "open": open_count,
            "closed": closed_count,
            "total_at_risk_usd": round(total_at_risk, 2),
            "total_potential_usd": round(total_potential, 2),
            "potential_multiplier": round(total_potential / total_at_risk, 2) if total_at_risk else None,
            "realized_pnl_usd": round(total_realized_pnl, 2),
            "positions": positions,
        }



    @mcp.tool()
    def open_signals(limit: int = 50) -> dict:
        """List signals awaiting resolution, newest first."""
        _ensure_db()
        with db.connect() as conn:
            rows = conn.execute("""
                SELECT s.*, m.question, m.end_date,
                       COALESCE(
                           s.side_entry_price,
                           CASE WHEN s.side = 'NO'
                                THEN 1.0 - s.yes_price_at_signal
                                ELSE s.yes_price_at_signal END
                       ) AS display_side_entry_price,
                       COALESCE(s.yes_equivalent_entry, s.yes_price_at_signal) AS display_yes_equivalent_entry
                FROM signals s JOIN markets m ON m.condition_id = s.condition_id
                WHERE s.resolved = 0
                ORDER BY s.created_at DESC LIMIT ?
            """, (limit,)).fetchall()
        out = [{
            "id": r["id"], "created": r["created_at"][:10],
            "side": r["side"], "question": r["question"],
            "entry_price": r["display_side_entry_price"],
            "yes_equivalent_entry": r["display_yes_equivalent_entry"],
            "claude_prob": r["claude_prob"],
            "edge": r["edge"], "confidence": r["confidence"], "bet": r["bet_amount"],
            "end_date": r["end_date"],
        } for r in rows]
        return {"count": len(out), "signals": out}



    @mcp.tool()
    async def resolve_closed() -> dict:
        """
        For every market with an open signal that has since closed on Polymarket,
        fetch the resolution outcome and compute realized PnL on the paper bet.
        Idempotent — already-resolved signals are skipped.
        """
        _ensure_db()
        GAMMA = "https://gamma-api.polymarket.com"

        with db.connect() as conn:
            rows = conn.execute("""
                SELECT DISTINCT s.condition_id
                FROM signals s JOIN markets m ON m.condition_id = s.condition_id
                WHERE s.resolved = 0 AND m.resolved = 0
            """).fetchall()
            cids = [r["condition_id"] for r in rows]

        resolved_now = 0
        async with httpx.AsyncClient(timeout=20) as http:
            for cid in cids:
                try:
                    r = await http.get(f"{GAMMA}/markets", params={"condition_ids": cid})
                    data = r.json()
                    items = data if isinstance(data, list) else data.get("data", [])
                    if not items:
                        continue
                    m = items[0]
                    if not m.get("closed"):
                        continue
                    prices = m.get("outcomePrices")
                    if isinstance(prices, str):
                        prices = json.loads(prices)
                    if not prices or len(prices) < 2:
                        continue
                    yes = float(prices[0])
                    with db.connect() as conn:
                        conn.execute("""
                            UPDATE markets SET resolved = 1, resolved_yes = ?, resolved_at = ?
                            WHERE condition_id = ?
                        """, (yes, datetime.now(timezone.utc).isoformat(), cid))
                        conn.commit()
                    resolved_now += 1
                except Exception:
                    continue

        # Compute PnL on the now-resolved signals
        pnl_updated = 0
        with db.connect() as conn:
            sigs = conn.execute("""
                SELECT s.id, s.side, COALESCE(s.yes_equivalent_entry, s.yes_price_at_signal) AS yes_equivalent_entry,
                       s.bet_amount, m.resolved_yes
                FROM signals s JOIN markets m ON m.condition_id = s.condition_id
                WHERE s.resolved = 0 AND m.resolved = 1
            """).fetchall()
            for s in sigs:
                pnl = _realized_pnl(
                    side=s["side"],
                    entry_price=s["yes_equivalent_entry"],
                    bet_amount=s["bet_amount"],
                    resolved_yes=s["resolved_yes"],
                )
                conn.execute("UPDATE signals SET resolved = 1, realized_pnl = ? WHERE id = ?",
                             (round(pnl, 2), s["id"]))
                pnl_updated += 1
            conn.commit()

        return {"markets_resolved": resolved_now, "signals_priced": pnl_updated}



    @mcp.tool()
    def vertical_breakdown() -> dict:
        """
        Per-vertical performance summary: signal counts, win rate, ROI, avg edge.
        Use to decide which vertical to allocate more research/bankroll toward.
        """
        _ensure_db()
        out = {}
        with db.connect() as conn:
            verticals = [r["v"] for r in conn.execute(
                "SELECT DISTINCT COALESCE(vertical,'unknown') AS v FROM markets"
            ).fetchall()]
            for v in verticals:
                rows = conn.execute("""
                    SELECT s.resolved, s.realized_pnl, s.bet_amount, s.edge
                    FROM signals s JOIN markets m ON m.condition_id = s.condition_id
                    WHERE COALESCE(m.vertical,'unknown') = ?
                """, (v,)).fetchall()
                total = len(rows)
                closed = [r for r in rows if r["resolved"]]
                wins = sum(1 for r in closed if (r["realized_pnl"] or 0) > 0)
                pnl = sum(r["realized_pnl"] or 0 for r in closed)
                wagered = sum(r["bet_amount"] for r in closed) or 0.0
                avg_edge = (sum(r["edge"] for r in rows) / total) if total else 0.0
                out[v] = {
                    "total_signals": total,
                    "open": total - len(closed),
                    "closed": len(closed),
                    "wins": wins,
                    "win_rate_pct": round(wins / len(closed) * 100, 1) if closed else None,
                    "pnl_usd": round(pnl, 2),
                    "roi_pct": round(pnl / wagered * 100, 1) if wagered else None,
                    "avg_edge_pct": round(avg_edge * 100, 2),
                }
        return out


