"""Auto-generated by Stage 0 splitter. Tools registered by mcp_server.register_all(mcp)."""
from __future__ import annotations
import asyncio
import json
import math
from datetime import datetime, timezone

import httpx

import config
import db
from markets import fetch_active_markets

from lib.execution import (
    clamp01 as _clamp01,
    float_or_none as _float_or_none,
    execution_prices as _execution_prices,
    best_executable_edge as _best_executable_edge,
    no_signal_reason as _no_signal_reason,
)
from lib.queries import (
    latest_probability as _latest_probability,
    latest_execution_context as _latest_execution_context,
    market_row as _market_row,
    research_completeness as _research_completeness,
)
from lib.scoring import (
    hidden_gem_score as _hidden_gem_score,
    moonshot_score as _moonshot_score,
    resolution_completeness as _resolution_completeness,
    pre_bet_score as _pre_bet_score,
    signal_quality_score as _signal_quality_score,
    log_score as _log_score,
    quality_grade as _quality_grade,
    parse_dt as _parse_dt,
)
from lib.sizing import recommended_stake as _recommended_stake
from lib.gates import validate_signal_gate as _validate_signal_gate


def _today() -> str:
    return datetime.now(timezone.utc).date().isoformat()


def _ensure_db() -> None:
    db.init()


SIGNAL_ARCHETYPES = {
    "countable_catalyst",
    "cheap_optionality",
    "resolution_wording_trap",
    "stale_price",
    "actor_incentive_mismatch",
    "crowd_narrative_error",
    "repricing_watch",
}


def register(mcp):
    @mcp.tool()
    def record_analysis(
        condition_id: str,
        probability_yes: float,
        confidence: float,
        reasoning: str,
        sources: list[str] | None = None,
        require_pre_bet_approval: bool = True,
        dry_run: bool = False,
    ) -> dict:
        """
        Record Claude's calibrated probability estimate for a market.
        Computes edge vs current market price. A paper signal is emitted only
        when numeric gates pass AND the latest pre-bet checklist approved it.
        Always logs the analysis itself, including no-signal decisions, so
        calibration and false-negative analysis are possible.

        Args:
            condition_id: from fetch_candidates output
            probability_yes: your calibrated estimate (0.0-1.0). Don't anchor to market price.
            confidence: 0.0-1.0. Be honest. <0.35 means low confidence; no signal will fire.
            reasoning: 2-4 sentences explaining the key evidence and how it shaped the estimate
            sources: list of URLs/publications you relied on
            require_pre_bet_approval: require latest pre-bet checklist decision
                to be approved_for_signal before a paper position is created.
            dry_run: evaluate gates/sizing without writing signal, position,
                fill, or analysis rows.

        Returns:
            {"signal_emitted": bool, "side": "YES"|"NO"|null, "edge": float,
             "bet_amount": float, "market_price": float, "signal_id": int|null}
        """
        _ensure_db()
        probability_yes = max(0.0, min(1.0, float(probability_yes)))
        confidence = max(0.0, min(1.0, float(confidence)))
        sources = sources or []

        with db.connect() as conn:
            row = conn.execute("""
                SELECT yes_price, no_price, best_bid, best_ask, spread,
                       yes_entry_price, no_entry_price, captured_at,
                       (julianday('now') - julianday(captured_at)) * 24.0 * 60.0 AS age_min
                FROM snapshots
                WHERE condition_id = ?
                ORDER BY captured_at DESC LIMIT 1
            """, (condition_id,)).fetchone()
            if not row:
                return {"error": f"no snapshot for {condition_id}; call fetch_candidates first"}
            age_min = row["age_min"]
            if age_min is not None and age_min > config.MAX_SNAPSHOT_AGE_MIN:
                return {
                    "error": "snapshot_stale_call_fetch_candidates",
                    "snapshot_age_min": round(float(age_min), 1),
                    "max_snapshot_age_min": config.MAX_SNAPSHOT_AGE_MIN,
                }
            market_price = float(row["yes_price"])
            no_price = float(row["no_price"]) if row["no_price"] is not None else 1.0 - market_price
            yes_entry_price = float(row["yes_entry_price"]) if row["yes_entry_price"] is not None else market_price
            no_entry_price = float(row["no_entry_price"]) if row["no_entry_price"] is not None else no_price
            spread = float(row["spread"]) if row["spread"] is not None else None

            mid_edge = probability_yes - market_price
            side, executable_edge = _best_executable_edge(
                probability_yes, yes_entry_price, no_entry_price
            )
            no_signal_reason = _no_signal_reason(executable_edge, confidence, spread)

            signal_emitted = False
            would_emit_signal = False
            signal_side: str | None = None
            bet_amount = 0.0
            signal_id: int | None = None

            sizing_info = None
            checklist_gate = None
            signal_gate = None
            enforce_pre_bet_approval = require_pre_bet_approval or not dry_run
            if no_signal_reason is None:
                signal_side = side
                if enforce_pre_bet_approval:
                    signal_gate = _validate_signal_gate(
                        conn,
                        condition_id=condition_id,
                        probability_yes=probability_yes,
                        confidence=confidence,
                        intended_side=side,
                    )
                    checklist_gate = signal_gate.get("latest_pre_bet_checklist")
                    if not signal_gate["ok"]:
                        blockers = signal_gate.get("blockers") or []
                        if "missing_pre_bet_checklist" in blockers:
                            no_signal_reason = "missing_pre_bet_checklist"
                        elif any(str(b).startswith("pre_bet_") for b in blockers):
                            no_signal_reason = next(str(b) for b in blockers if str(b).startswith("pre_bet_"))
                        else:
                            no_signal_reason = "signal_gate_blocked:" + ",".join(blockers[:3])

            if no_signal_reason is None:
                signal_side = side
                # Stage 1: portfolio-aware sizing. Look up vertical/end_date so
                # shrinkage applies to the right buckets.
                market_meta = conn.execute(
                    "SELECT vertical, end_date FROM markets WHERE condition_id = ?",
                    (condition_id,),
                ).fetchone()
                theme_tags = db.get_market_tags(conn, condition_id)
                sizing_info = _recommended_stake(
                    edge=executable_edge,
                    confidence=confidence,
                    conn=conn,
                    condition_id=condition_id,
                    vertical=market_meta["vertical"] if market_meta else "unknown",
                    primary_archetype=None,  # filled in later by record_signal_archetype
                    end_date=market_meta["end_date"] if market_meta else None,
                    theme_tags=theme_tags,
                )
                bet_amount = sizing_info["recommended"]
                if not dry_run:
                    yes_equivalent_entry = yes_entry_price if signal_side == "YES" else 1.0 - no_entry_price
                    side_entry_price = yes_entry_price if signal_side == "YES" else no_entry_price
                    signal_id = db.add_signal(
                        conn,
                        condition_id=condition_id, created_at=None,
                        model="claude-desktop-pro", yes_price_at_signal=yes_equivalent_entry,
                        yes_equivalent_entry=yes_equivalent_entry,
                        side_entry_price=side_entry_price,
                        claude_prob=probability_yes, confidence=confidence,
                        side=signal_side, edge=executable_edge, bet_amount=bet_amount,
                        reasoning=reasoning, sources_json=json.dumps(sources),
                        tokens_in=None, tokens_out=None, cache_read_tokens=None,
                        cost_usd=0.0,
                        gate_status="gated",
                        gate_audit_note="record_analysis enforced approved pre-bet gate",
                    )
                    # Stage 1: create the position + paper fill at the same time.
                    position_id = db.add_position(
                        conn,
                        condition_id=condition_id, signal_id=signal_id, opened_at=None,
                        intended_side=signal_side, intended_entry_price=side_entry_price,
                        side_entry_price=side_entry_price,
                        yes_equivalent_entry=yes_equivalent_entry,
                        intended_stake_usd=bet_amount, stake_source="paper",
                        status="open", thesis_snapshot_text=reasoning,
                        primary_archetype=None,
                        end_date=market_meta["end_date"] if market_meta else None,
                    )
                    shares = bet_amount / side_entry_price if side_entry_price else 0.0
                    db.add_fill(
                        conn, position_id=position_id, side=signal_side,
                        price=side_entry_price, shares=shares,
                        stake_usd=bet_amount, venue="paper", slippage_vs_intent=0.0,
                    )
                would_emit_signal = True
                signal_emitted = not dry_run

            analysis_id = None
            if not dry_run:
                analysis_id = db.add_analysis(
                    conn,
                    run_date=_today(),
                    condition_id=condition_id,
                    created_at=None,
                    analyst="claude-desktop",
                    model="claude-desktop-pro",
                    yes_price_at_analysis=market_price,
                    probability_yes=probability_yes,
                    confidence=confidence,
                    edge=executable_edge,
                    decision="signal" if signal_emitted else "no_signal",
                    no_signal_reason=no_signal_reason,
                    signal_id=signal_id,
                    reasoning=reasoning,
                    sources_json=json.dumps(sources),
                    notes="",
                )
                conn.commit()

        return {
            "analysis_id": analysis_id,
            "signal_emitted": signal_emitted,
            "would_emit_signal": would_emit_signal,
            "dry_run": dry_run,
            "side": signal_side,
            "candidate_side": side,
            "edge": round(executable_edge, 4),
            "mid_edge": round(mid_edge, 4),
            "no_signal_reason": no_signal_reason,
            "bet_amount": bet_amount,
            "market_price": market_price,
            "yes_entry_price": yes_entry_price,
            "no_entry_price": no_entry_price,
            "spread": spread,
            "claude_prob": probability_yes,
            "confidence": confidence,
            "signal_id": signal_id,
            "sizing": sizing_info,
            "pre_bet_gate": dict(checklist_gate) if checklist_gate is not None else None,
            "signal_gate": signal_gate,
            "require_pre_bet_approval": enforce_pre_bet_approval,
        }



    @mcp.tool()
    def record_evidence(
        condition_id: str,
        claim: str,
        stance: str = "NEUTRAL",
        source_url: str = "",
        source_name: str = "",
        published_at: str = "",
        strength: float = 0.5,
        reliability: float = 0.5,
        freshness: float = 0.5,
        notes: str = "",
    ) -> dict:
        """
        Add one evidence item to a market dossier.

        Use this before or alongside record_analysis. The point is to remember
        the actual claims that moved the forecast, not just the final probability.

        Args:
            stance: YES, NO, MIXED, or NEUTRAL.
            strength: how much the claim matters if true (0-1).
            reliability: source/claim reliability (0-1).
            freshness: how current the evidence is (0-1).
        """
        _ensure_db()
        stance = stance.upper()
        if stance not in {"YES", "NO", "MIXED", "NEUTRAL"}:
            return {"error": "stance must be YES, NO, MIXED, or NEUTRAL"}
        if not claim.strip():
            return {"error": "claim is required"}

        # Source registry auto-resolution: if caller didn't override reliability
        # (still at default 0.5) AND we can match the URL to a registered source,
        # use the registered source's reliability_score. Also bump times_cited.
        resolved_source_meta = None
        with db.connect() as conn:
            if source_url:
                resolved_source_meta = db.lookup_source_by_url(conn, source_url)
                if resolved_source_meta:
                    if reliability == 0.5:  # caller used default → adopt registered
                        reliability = float(resolved_source_meta["reliability_score"])
                    if not source_name:
                        source_name = resolved_source_meta["name"]
                    db.increment_source_citation(conn, resolved_source_meta["id"])

            market = conn.execute(
                "SELECT question FROM markets WHERE condition_id = ?", (condition_id,)
            ).fetchone()
            if not market:
                return {"error": f"market {condition_id} not found; call fetch_candidates first"}
            evidence_id = db.add_evidence(
                conn,
                condition_id=condition_id,
                created_at=None,
                source_url=source_url or None,
                source_name=source_name or None,
                published_at=published_at or None,
                claim=claim.strip(),
                stance=stance,
                strength=_clamp01(strength),
                reliability=_clamp01(reliability),
                freshness=_clamp01(freshness),
                notes=notes,
            )
            counts = conn.execute("""
                SELECT stance, COUNT(*) AS n
                FROM evidence
                WHERE condition_id = ?
                GROUP BY stance
            """, (condition_id,)).fetchall()
            conn.commit()

        return {
            "ok": True,
            "evidence_id": evidence_id,
            "condition_id": condition_id,
            "question": market["question"],
            "evidence_balance": {r["stance"]: r["n"] for r in counts},
            "resolved_source": (
                {"name": resolved_source_meta["name"],
                 "type": resolved_source_meta["source_type"],
                 "bias": resolved_source_meta["bias"],
                 "reliability_applied": resolved_source_meta["reliability_score"]}
                if resolved_source_meta else None
            ),
        }



    @mcp.tool()
    def record_forecast_update(
        condition_id: str,
        updated_probability_yes: float,
        reason: str,
        trigger: str = "",
        sources: list[str] | None = None,
        analysis_id: int | None = None,
    ) -> dict:
        """
        Record a probability revision without overwriting the old view.

        Use this when a source, price move, contradiction, or catalyst changes the
        thesis. This creates a forecast history so the project can later study how
        beliefs evolved before resolution.
        """
        _ensure_db()
        updated_probability_yes = _clamp01(updated_probability_yes)
        sources = sources or []
        if not reason.strip():
            return {"error": "reason is required"}

        with db.connect() as conn:
            market = conn.execute(
                "SELECT question FROM markets WHERE condition_id = ?", (condition_id,)
            ).fetchone()
            if not market:
                return {"error": f"market {condition_id} not found; call fetch_candidates first"}
            previous = _latest_probability(conn, condition_id)
            delta = None if previous is None else updated_probability_yes - previous
            update_id = db.add_forecast_update(
                conn,
                condition_id=condition_id,
                created_at=None,
                previous_probability_yes=previous,
                updated_probability_yes=updated_probability_yes,
                delta=delta,
                trigger=trigger or None,
                reason=reason.strip(),
                sources_json=json.dumps(sources),
                analysis_id=analysis_id,
            )
            conn.commit()

        return {
            "ok": True,
            "update_id": update_id,
            "condition_id": condition_id,
            "question": market["question"],
            "previous_probability_yes": previous,
            "updated_probability_yes": updated_probability_yes,
            "delta": round(delta, 4) if delta is not None else None,
            "material_change": abs(delta) >= 0.03 if delta is not None else None,
        }



    @mcp.tool()
    def market_research_memory(condition_id: str) -> dict:
        """
        Return the full research dossier for one market: latest price context,
        analyses, evidence, forecast updates, hidden-gem reviews, and signals.
        """
        _ensure_db()
        with db.connect() as conn:
            market = conn.execute("""
                SELECT * FROM markets WHERE condition_id = ?
            """, (condition_id,)).fetchone()
            if not market:
                return {"error": f"market {condition_id} not found"}
            ctx = _latest_execution_context(conn, condition_id)
            analyses = conn.execute("""
                SELECT id, created_at, probability_yes, confidence, edge, decision,
                       no_signal_reason, signal_id, reasoning
                FROM analyses
                WHERE condition_id = ?
                ORDER BY created_at DESC LIMIT 10
            """, (condition_id,)).fetchall()
            evidence = conn.execute("""
                SELECT id, created_at, source_url, source_name, published_at, claim,
                       stance, strength, reliability, freshness, notes
                FROM evidence
                WHERE condition_id = ?
                ORDER BY created_at DESC LIMIT 20
            """, (condition_id,)).fetchall()
            updates = conn.execute("""
                SELECT id, created_at, previous_probability_yes, updated_probability_yes,
                       delta, trigger, reason, sources_json
                FROM forecast_updates
                WHERE condition_id = ?
                ORDER BY created_at DESC LIMIT 10
            """, (condition_id,)).fetchall()
            reviews = conn.execute("""
                SELECT *
                FROM hidden_gem_reviews
                WHERE condition_id = ?
                ORDER BY created_at DESC LIMIT 10
            """, (condition_id,)).fetchall()
            actors = conn.execute("""
                SELECT *
                FROM actor_maps
                WHERE condition_id = ?
                ORDER BY influence_score DESC, created_at DESC LIMIT 20
            """, (condition_id,)).fetchall()
            factors = conn.execute("""
                SELECT *
                FROM causal_factors
                WHERE condition_id = ?
                ORDER BY importance DESC, created_at DESC LIMIT 20
            """, (condition_id,)).fetchall()
            anomalies = conn.execute("""
                SELECT *
                FROM anomalies
                WHERE condition_id = ?
                ORDER BY severity DESC, created_at DESC LIMIT 20
            """, (condition_id,)).fetchall()
            scenarios = conn.execute("""
                SELECT *
                FROM scenario_trees
                WHERE condition_id = ?
                ORDER BY probability DESC, created_at DESC LIMIT 20
            """, (condition_id,)).fetchall()
            premortems = conn.execute("""
                SELECT *
                FROM premortems
                WHERE condition_id = ?
                ORDER BY severity DESC, created_at DESC LIMIT 20
            """, (condition_id,)).fetchall()
            signals = conn.execute("""
                SELECT id, created_at, side, yes_price_at_signal, claude_prob,
                       confidence, edge, bet_amount, resolved, realized_pnl
                FROM signals
                WHERE condition_id = ?
                ORDER BY created_at DESC LIMIT 10
            """, (condition_id,)).fetchall()

        return {
            "condition_id": condition_id,
            "question": market["question"],
            "vertical": market["vertical"],
            "end_date": market["end_date"],
            "latest_execution_context": ctx,
            "latest_probability_yes": None if not analyses and not updates else (
                updates[0]["updated_probability_yes"]
                if updates and (not analyses or updates[0]["created_at"] >= analyses[0]["created_at"])
                else analyses[0]["probability_yes"]
            ),
            "analyses": [dict(r) for r in analyses],
            "evidence": [dict(r) for r in evidence],
            "forecast_updates": [
                {**dict(r), "sources": json.loads(r["sources_json"]) if r["sources_json"] else []}
                for r in updates
            ],
            "hidden_gem_reviews": [dict(r) for r in reviews],
            "actors": [dict(r) for r in actors],
            "causal_factors": [dict(r) for r in factors],
            "anomalies": [dict(r) for r in anomalies],
            "scenarios": [dict(r) for r in scenarios],
            "premortems": [dict(r) for r in premortems],
            "signals": [dict(r) for r in signals],
        }
